/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slit;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane; 
import static slit.client.foreleser.mainWindowForeleser.getGenerellModul;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author Sondre, Michael, Erik, Christian Fredrik, Thomas, Gruppe 109
 * GUI for student, mainWindow. Her ligger det meste av GUI og en del logikk.
 * Vi begynte å forandre på strukturen for å redusere logikk i GUI-klasser, men rakk ikke gjøre endringer for hele systemet.
 */
public class mainWindow extends javax.swing.JFrame {
Connection connection=null;
PreparedStatement ps=null;
ResultSet rs=null;
String filePath=null;
    /**
     * Creates new form mainWindow
     */
    private static String modulTrykket = "";

    public static String getModulTrykket() {
        return modulTrykket;
    }

    public  void setModulTrykket(String modulTrykket) {
        this.modulTrykket = modulTrykket;
    }
    private String user = "";
    private String pass ="";
    private String ukeString = "";
    private String gått = "";
    private String annerledes ="";
    private String hjelp = "";
    private String timerString = "";
    int timer = 0;
    int uke = 0;
    int statusId = 0;
    final static String newline = "\n";
    public mainWindow() {
        initComponents();
        statistikkVisning();
        profilVisning();
        db.hentGammelBeskjed();
        hentMøte();
        hentDagens();
        displayPhoto();
        visInnleveringer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToggleButton1 = new javax.swing.JToggleButton();
        fileChooser = new javax.swing.JFileChooser();
        jPanelTopMain = new javax.swing.JPanel();
        jPanelTopCentre = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTittel = new javax.swing.JLabel();
        jPanelTopTop = new javax.swing.JPanel();
        jPanelTopBot = new javax.swing.JPanel();
        jSeperatorTopBot = new javax.swing.JSeparator();
        jPanelLeftMain = new javax.swing.JPanel();
        jPanelLeftLeft = new javax.swing.JPanel();
        jSeperatorLeftLeft = new javax.swing.JSeparator();
        jPanelLeftCentre = new javax.swing.JPanel();
        jScrollPaneMeny = new javax.swing.JScrollPane();
        jTreeMeny = new javax.swing.JTree();
        jPanelLeftRight = new javax.swing.JPanel();
        jSeperatorLeftRight = new javax.swing.JSeparator();
        jPanelBotMain = new javax.swing.JPanel();
        jTabbedPaneInnleveringer = new javax.swing.JTabbedPane();
        jPanelHjem = new javax.swing.JPanel();
        jPanelDagensMain = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaDagens = new javax.swing.JTextArea();
        jPanelModuler = new javax.swing.JPanel();
        jScrollPaneModuloversikt = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jLabelModuler109 = new javax.swing.JLabel();
        jButtonModul1 = new javax.swing.JButton();
        jButtonModul2 = new javax.swing.JButton();
        jButtonModul3 = new javax.swing.JButton();
        jButtonModul4 = new javax.swing.JButton();
        jButtonModul5 = new javax.swing.JButton();
        jLabelModuler110 = new javax.swing.JLabel();
        jButtonModul6 = new javax.swing.JButton();
        jButtonModul7 = new javax.swing.JButton();
        jButtonModul8 = new javax.swing.JButton();
        jButtonModul9 = new javax.swing.JButton();
        jButtonModul10 = new javax.swing.JButton();
        jButtonModul11 = new javax.swing.JButton();
        jButtonModul12 = new javax.swing.JButton();
        jButtonModul13 = new javax.swing.JButton();
        jButtonModul14 = new javax.swing.JButton();
        jPanelStatistikk = new javax.swing.JPanel();
        jPanelStatistikkMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaId = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaName = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSurname = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDate = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaLeverte = new javax.swing.JTextArea();
        jPanelMøte = new javax.swing.JPanel();
        jButtonBestill = new javax.swing.JButton();
        jButtonAvbestill = new javax.swing.JButton();
        jPanelMøteTop = new javax.swing.JPanel();
        jPanelMøtebot = new javax.swing.JPanel();
        jPanelMøteRight = new javax.swing.JPanel();
        jPanelMøteCentre = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jListMøte = new javax.swing.JList();
        jPanelStatusrapport = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion1 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion3 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion5 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaGått = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaHjelp = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextAreaAnnerledes = new javax.swing.JTextArea();
        jButtonSendRapport = new javax.swing.JButton();
        jLabelStatusrapportQuestion2 = new javax.swing.JLabel();
        jPanelRightMain = new javax.swing.JPanel();
        jTextFieldUke = new javax.swing.JTextField();
        jTextFieldTimer = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaModulResultat = new javax.swing.JTextArea();
        mainRight = new javax.swing.JPanel();
        profilTitle = new javax.swing.JLabel();
        profilbilde = new javax.swing.JLabel();
        testProfil = new javax.swing.JButton();
        profilnavnLabel = new javax.swing.JLabel();
        profilrolleLabel = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTopMain.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slit/UiA logo_middels_None.jpg"))); // NOI18N

        jLabelTittel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabelTittel.setText("Programmeringsprosjekt IS-202, Gruppe 109");

        javax.swing.GroupLayout jPanelTopCentreLayout = new javax.swing.GroupLayout(jPanelTopCentre);
        jPanelTopCentre.setLayout(jPanelTopCentreLayout);
        jPanelTopCentreLayout.setHorizontalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabelTittel)
                .addContainerGap(1091, Short.MAX_VALUE))
        );
        jPanelTopCentreLayout.setVerticalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopCentreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTittel)
                .addGap(45, 45, 45))
        );

        jPanelTopMain.add(jPanelTopCentre, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelTopTopLayout = new javax.swing.GroupLayout(jPanelTopTop);
        jPanelTopTop.setLayout(jPanelTopTopLayout);
        jPanelTopTopLayout.setHorizontalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1989, Short.MAX_VALUE)
        );
        jPanelTopTopLayout.setVerticalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanelTopMain.add(jPanelTopTop, java.awt.BorderLayout.PAGE_START);

        jSeperatorTopBot.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorTopBot.setPreferredSize(new java.awt.Dimension(50, 1));

        javax.swing.GroupLayout jPanelTopBotLayout = new javax.swing.GroupLayout(jPanelTopBot);
        jPanelTopBot.setLayout(jPanelTopBotLayout);
        jPanelTopBotLayout.setHorizontalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1989, Short.MAX_VALUE)
        );
        jPanelTopBotLayout.setVerticalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBotLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanelTopMain.add(jPanelTopBot, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanelTopMain, java.awt.BorderLayout.PAGE_START);

        jPanelLeftLeft.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftLeft.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftLeft.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftLeft.add(jSeperatorLeftLeft, java.awt.BorderLayout.CENTER);

        jPanelLeftCentre.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Hurtignavigering");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Moduler");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Moduloversikt");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduler IS-109");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 1");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 2");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 3");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 4");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduer IS-110");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 6");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 7");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 8");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 9");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 10");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 11");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 12");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 13");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 14");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("osv");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Møte");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Statusrapport");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Hjelp");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("FAQ");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Forum");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("IM");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Om systemet");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeMeny.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeMeny.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPaneMeny.setViewportView(jTreeMeny);

        jPanelLeftCentre.add(jScrollPaneMeny, java.awt.BorderLayout.CENTER);

        jPanelLeftRight.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftRight.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftRight.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftRight.add(jSeperatorLeftRight, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelLeftMainLayout = new javax.swing.GroupLayout(jPanelLeftMain);
        jPanelLeftMain.setLayout(jPanelLeftMainLayout);
        jPanelLeftMainLayout.setHorizontalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLeftRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelLeftMainLayout.setVerticalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
            .addComponent(jPanelLeftRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLeftMain, java.awt.BorderLayout.LINE_START);
        getContentPane().add(jPanelBotMain, java.awt.BorderLayout.PAGE_END);

        jTabbedPaneInnleveringer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneInnleveringerMouseClicked(evt);
            }
        });

        jPanelDagensMain.setLayout(new java.awt.GridBagLayout());

        jScrollPane9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dagens", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jTextAreaDagens.setEditable(false);
        jTextAreaDagens.setColumns(20);
        jTextAreaDagens.setRows(5);
        jScrollPane9.setViewportView(jTextAreaDagens);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 510;
        gridBagConstraints.ipady = 329;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanelDagensMain.add(jScrollPane9, gridBagConstraints);

        javax.swing.GroupLayout jPanelHjemLayout = new javax.swing.GroupLayout(jPanelHjem);
        jPanelHjem.setLayout(jPanelHjemLayout);
        jPanelHjemLayout.setHorizontalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHjemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDagensMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(859, Short.MAX_VALUE))
        );
        jPanelHjemLayout.setVerticalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHjemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDagensMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jTabbedPaneInnleveringer.addTab("Hjem", jPanelHjem);

        jTextAreaInfo.setEditable(false);
        jTextAreaInfo.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaInfo.setColumns(20);
        jTextAreaInfo.setRows(5);
        jTextAreaInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneModuloversikt.setViewportView(jTextAreaInfo);

        jLabelModuler109.setText("Moduler IS-109");

        jButtonModul1.setText("Modul 1");
        jButtonModul1.setMaximumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setMinimumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul1ActionPerformed(evt);
            }
        });

        jButtonModul2.setText("Modul 2");
        jButtonModul2.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul2ActionPerformed(evt);
            }
        });

        jButtonModul3.setText("Modul 3");
        jButtonModul3.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul3ActionPerformed(evt);
            }
        });

        jButtonModul4.setText("Modul 4");
        jButtonModul4.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul4ActionPerformed(evt);
            }
        });

        jButtonModul5.setText("Modul 5");
        jButtonModul5.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul5ActionPerformed(evt);
            }
        });

        jLabelModuler110.setText("Moduler IS-110");

        jButtonModul6.setText("Modul 6");
        jButtonModul6.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul6ActionPerformed(evt);
            }
        });

        jButtonModul7.setText("Modul 7");
        jButtonModul7.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul7ActionPerformed(evt);
            }
        });

        jButtonModul8.setText("Modul 8");
        jButtonModul8.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul8ActionPerformed(evt);
            }
        });

        jButtonModul9.setText("Modul 9");
        jButtonModul9.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul9ActionPerformed(evt);
            }
        });

        jButtonModul10.setText("Modul 10");
        jButtonModul10.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul10ActionPerformed(evt);
            }
        });

        jButtonModul11.setText("Modul 11");
        jButtonModul11.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul11ActionPerformed(evt);
            }
        });

        jButtonModul12.setText("Modul 12");
        jButtonModul12.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul12ActionPerformed(evt);
            }
        });

        jButtonModul13.setText("Modul 13");
        jButtonModul13.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul13ActionPerformed(evt);
            }
        });

        jButtonModul14.setText("Modul 14");
        jButtonModul14.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModulerLayout = new javax.swing.GroupLayout(jPanelModuler);
        jPanelModuler.setLayout(jPanelModulerLayout);
        jPanelModulerLayout.setHorizontalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonModul4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelModuler109, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModul3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModul5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonModul6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModul14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModul7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModul8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModul9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModul10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModul11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModul12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelModuler110, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonModul13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(742, Short.MAX_VALUE))
        );
        jPanelModulerLayout.setVerticalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModuler109)
                            .addComponent(jLabelModuler110))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jTabbedPaneInnleveringer.addTab("Moduler", jPanelModuler);

        jPanelStatistikk.setLayout(new java.awt.BorderLayout());

        jPanelStatistikkMain.setLayout(new javax.swing.BoxLayout(jPanelStatistikkMain, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaId.setEditable(false);
        jTextAreaId.setColumns(20);
        jTextAreaId.setRows(5);
        jScrollPane2.setViewportView(jTextAreaId);

        jPanelStatistikkMain.add(jScrollPane2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaName.setEditable(false);
        jTextAreaName.setColumns(20);
        jTextAreaName.setRows(5);
        jScrollPane3.setViewportView(jTextAreaName);

        jPanelStatistikkMain.add(jScrollPane3);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaSurname.setEditable(false);
        jTextAreaSurname.setColumns(20);
        jTextAreaSurname.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSurname);

        jPanelStatistikkMain.add(jScrollPane4);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaDate.setEditable(false);
        jTextAreaDate.setColumns(20);
        jTextAreaDate.setRows(5);
        jScrollPane5.setViewportView(jTextAreaDate);

        jPanelStatistikkMain.add(jScrollPane5);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaLeverte.setEditable(false);
        jTextAreaLeverte.setColumns(20);
        jTextAreaLeverte.setRows(5);
        jScrollPane6.setViewportView(jTextAreaLeverte);

        jPanelStatistikkMain.add(jScrollPane6);

        jPanelStatistikk.add(jPanelStatistikkMain, java.awt.BorderLayout.CENTER);

        jTabbedPaneInnleveringer.addTab("Statistikk", jPanelStatistikk);

        jPanelMøte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMøteMouseClicked(evt);
            }
        });

        jButtonBestill.setText("Bestill møte");

        jButtonAvbestill.setText("Avbestill møte");

        jPanelMøteTop.setLayout(new javax.swing.BoxLayout(jPanelMøteTop, javax.swing.BoxLayout.LINE_AXIS));

        jPanelMøtebot.setLayout(new javax.swing.BoxLayout(jPanelMøtebot, javax.swing.BoxLayout.LINE_AXIS));

        jPanelMøteRight.setLayout(new javax.swing.BoxLayout(jPanelMøteRight, javax.swing.BoxLayout.LINE_AXIS));

        jPanelMøteCentre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Møteplan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jListMøte.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane14.setViewportView(jListMøte);

        javax.swing.GroupLayout jPanelMøteCentreLayout = new javax.swing.GroupLayout(jPanelMøteCentre);
        jPanelMøteCentre.setLayout(jPanelMøteCentreLayout);
        jPanelMøteCentreLayout.setHorizontalGroup(
            jPanelMøteCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMøteCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMøteCentreLayout.setVerticalGroup(
            jPanelMøteCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMøteLayout = new javax.swing.GroupLayout(jPanelMøte);
        jPanelMøte.setLayout(jPanelMøteLayout);
        jPanelMøteLayout.setHorizontalGroup(
            jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMøteLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButtonBestill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAvbestill)
                .addGap(28, 28, 28)
                .addComponent(jPanelMøteCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283)
                .addComponent(jPanelMøteTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanelMøtebot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanelMøteRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(454, 454, 454))
        );
        jPanelMøteLayout.setVerticalGroup(
            jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMøteLayout.createSequentialGroup()
                .addGroup(jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMøteLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAvbestill)
                            .addComponent(jButtonBestill)))
                    .addGroup(jPanelMøteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanelMøtebot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMøteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanelMøteRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMøteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanelMøteCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelMøteTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(376, Short.MAX_VALUE))
        );

        jTabbedPaneInnleveringer.addTab("Møte", jPanelMøte);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Statusrapport:");

        jLabelStatusrapportQuestion1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion1.setText("Hvilken uke rapporterer du for?");

        jLabelStatusrapportQuestion3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion3.setText("Hva kunne blitt gjort annerledes?");

        jLabelStatusrapportQuestion5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion5.setText("Hvor mange timer har du jobbet denne uken?");

        jLabelStatusrapportQuestion4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion4.setText("Spesielle problemer eller ønske om forelesningstema?");

        jTextAreaGått.setColumns(20);
        jTextAreaGått.setRows(5);
        jScrollPane7.setViewportView(jTextAreaGått);

        jTextAreaHjelp.setColumns(20);
        jTextAreaHjelp.setRows(5);
        jScrollPane8.setViewportView(jTextAreaHjelp);

        jTextAreaAnnerledes.setColumns(20);
        jTextAreaAnnerledes.setRows(5);
        jScrollPane10.setViewportView(jTextAreaAnnerledes);

        jButtonSendRapport.setText("Send/lagre");
        jButtonSendRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendRapportActionPerformed(evt);
            }
        });

        jLabelStatusrapportQuestion2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion2.setText("Hvordan har det gått?");

        javax.swing.GroupLayout jPanelRightMainLayout = new javax.swing.GroupLayout(jPanelRightMain);
        jPanelRightMain.setLayout(jPanelRightMainLayout);
        jPanelRightMainLayout.setHorizontalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
        jPanelRightMainLayout.setVerticalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelStatusrapportLayout = new javax.swing.GroupLayout(jPanelStatusrapport);
        jPanelStatusrapport.setLayout(jPanelStatusrapportLayout);
        jPanelStatusrapportLayout.setHorizontalGroup(
            jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusrapportLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelStatusrapportQuestion1)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(jLabelStatusrapportQuestion5)
                        .addComponent(jLabelStatusrapportQuestion2)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(jLabelStatusrapportQuestion3)
                        .addComponent(jLabelStatusrapportQuestion4)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(jTextFieldUke)
                        .addComponent(jTextFieldTimer))
                    .addComponent(jButtonSendRapport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 913, Short.MAX_VALUE)
                .addComponent(jPanelRightMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelStatusrapportLayout.setVerticalGroup(
            jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelStatusrapportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStatusrapportQuestion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabelStatusrapportQuestion2)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabelStatusrapportQuestion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatusrapportQuestion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatusrapportQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSendRapport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelStatusrapportLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanelRightMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneInnleveringer.addTab("Statusrapport", jPanelStatusrapport);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Oversikt over innleveringer som har gjennomgått sensur");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(835, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1565, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jTextAreaModulResultat.setEditable(false);
        jTextAreaModulResultat.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaModulResultat.setColumns(20);
        jTextAreaModulResultat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaModulResultat);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(741, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        jTabbedPaneInnleveringer.addTab("Mine innleveringer", jPanel1);

        getContentPane().add(jTabbedPaneInnleveringer, java.awt.BorderLayout.CENTER);

        profilTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        profilTitle.setForeground(new java.awt.Color(0, 0, 204));
        profilTitle.setText("Profil");

        testProfil.setText("Last Opp Profilbilde");
        testProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testProfilActionPerformed(evt);
            }
        });

        profilnavnLabel.setText("jLabel2");

        profilrolleLabel.setText("jLabel2");

        javax.swing.GroupLayout mainRightLayout = new javax.swing.GroupLayout(mainRight);
        mainRight.setLayout(mainRightLayout);
        mainRightLayout.setHorizontalGroup(
            mainRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainRightLayout.createSequentialGroup()
                .addGroup(mainRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainRightLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(profilTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(mainRightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profilnavnLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(testProfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profilrolleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainRightLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(profilbilde, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainRightLayout.setVerticalGroup(
            mainRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainRightLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(profilTitle)
                .addGap(18, 18, 18)
                .addComponent(profilnavnLabel)
                .addGap(18, 18, 18)
                .addComponent(profilrolleLabel)
                .addGap(18, 18, 18)
                .addComponent(profilbilde, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(testProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        getContentPane().add(mainRight, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Henter ut statistikken for "Statistikk" tab i GUI
     */
    public void statistikkVisning() {
        try {

            String db_url = "jdbc:mysql://localhost:3306/slit";
            String db_user = "root";
            String db_pass = "root";
            
            System.out.println("The URL is: " + db_url);
            Connection con = DriverManager.getConnection(db_url, db_user, db_pass);
            
            Statement stmt = con.createStatement( );
            String SQL ="SELECT * FROM Statistikk";
            ResultSet result = stmt.executeQuery (SQL);
            
            int id_col = 0;
            String name = "";
            String surname ="";
            String dato = "";
            int antLeverte = 0;

            while (result.next() ) {
                id_col = result.getInt("Bruker_brukerId");
                name = result.getString("brukerFornavn");
                surname = result.getString("brukerEtternavn");
                dato = result.getString("modulfilDato");
                antLeverte = result.getInt("COUNT(sensurId)");
              //  System.out.println("ID: "+ " " + id_col +"     " +  "Fornavn: " + 
              //      "     " + name + "     " + "Etternavn: " +" "+ surname + "     " 
              //          + "Dato og klokkeslett:" + " " + dato + "     "
              //      + "Antall godkjente moduler:" + antLeverte);
                
                jTextAreaId.append(" " + "Bruker ID:"+ " " + id_col + newline);
                jTextAreaName.append(" " + "Fornavn:" + " " + name + newline);
                jTextAreaSurname.append(" " + "Etternavn:" + " " + surname + newline);
                jTextAreaDate.append(" " + "Aktivitet:" + " " + dato + newline);
                jTextAreaLeverte.append(" " + "Moduler med sensur:" + " " + antLeverte + newline);
                /**
                " +  "Fornavn: " + 
                    " " + name + "          " + "Etternavn: " +" "+ surname + "          " 
                        + "Dato og klokkeslett:" + " " + dato + "          "
                    + "Antall godkjente moduler:" + antLeverte + " "
                        + newline);
                        * /
                        
                // For å gjøre int om til string, om det trengs
                /**
                StringBuilder ID = new StringBuilder();
                    ID.append("");
                    ID.append(id_col);
                    String idString = ID.toString();
                
                StringBuilder leverte = new StringBuilder();
                    leverte.append("");
                    leverte.append(antLeverte);
                    String antLeverteString = leverte.toString();
               */     
            }
            
            
            
            
           
        }
          catch (SQLException err) {
            System.out.println( err.getMessage( ));
            
        } 
       
        
    }
    /**
     * For å laste en brukers profil
     * @return 
     */
    public localUser profilVisning () {
        String user = Main.user.getUser();
        String rolle = Main.user.getRole();
        profilnavnLabel.setText("   " +user);
        profilrolleLabel.setText("   " + rolle);
        return Main.user;
    }
    /**
     * kaller metoden db.sendRapport, angitt i db.java
     */
    private void sendStatusrapport() {
        if (Main.user != null)
        db.sendRapport(uke, gått, annerledes, hjelp, timer);
              
    }
    /**
     * Henter dagens melding på startskjermen / hjem-tab når systemet starter
     */
    public void hentDagens() {
        try {
            
            String SQL = ("SELECT dagensBeskjed FROM dagens");
            Connection con = DriverManager.getConnection(Constants.db_url,Constants.db_user, Constants.db_pass);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(SQL);
            String dagensMelding = "";
            while (rs.next()) {
            dagensMelding = rs.getString("dagensBeskjed");
            jTextAreaDagens.append(dagensMelding);
            }
        }
        catch (SQLException err) {
            System.out.println(err);
        }
            
    }
    
    public void displayPhoto() {

    BufferedImage bufImg = null;
    
    {
    try
    {
        String url = "jdbc:mysql://localhost:3306/slit";
        String user = "root";
        String password = "root";
        Connection connection = DriverManager.getConnection(url, user, password);
        
        String sql = "select profilbildeBlob from profilbilde where Bruker_brukerId =?";
         
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setInt(1, slit.Main.user.getId());

        rs = statement.executeQuery();
        while (rs.next()) {
        InputStream in = rs.getBinaryStream("profilbildeBlob");
        bufImg = ImageIO.read(in);
        ImageIcon ii = new ImageIcon(bufImg);
        Image image = ii.getImage();
        image = image.getScaledInstance(187, 187, Image.SCALE_SMOOTH);
        ii = new ImageIcon(image);
        profilbilde.setIcon(ii);
        }
    
    }
    catch(Exception e)
    {    
    JOptionPane.showMessageDialog(null, e);
    }
    }
    
   
    }
    
    
        
    public void visInnleveringer() {
        try {
        String SQL = ("SELECT * FROM Sensur WHERE Bruker_brukerId = '"+Main.user.getId()+"'");
        Connection con = DriverManager.getConnection(Constants.db_url,Constants.db_user, Constants.db_pass);
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(SQL);
        String vurdering = "";
        int modulFilId = 0;
        String modulFilIdString = "";
        String resultat = "";
        String modul = "";
        while (rs.next()) {
            vurdering = rs.getString("sensurVurdering");
            modulFilIdString = String.valueOf(rs.getInt("Modulfil_modulfilId"));
            resultat = rs.getString("sensurResultat");
            modul = rs.getString("sensurModul");
            jTextAreaModulResultat.append ("Modul fil ID:" + " " + modulFilIdString + newline + 
                "Modul:" + " " + modul + newline +
                "Forelesers vurdering:" + " " +vurdering + newline +
                "Resultat:" + " " + resultat + newline + newline);
        }
                 
        }
        catch (SQLException err) {
            System.out.println(err);
        }
    }
    /**
     * Henter ut møtetider for møte-tab i GUI
     */
     public void hentMøte () {
         try {
            DefaultListModel DML = new DefaultListModel();
             Connection con = DriverManager.getConnection(Constants.db_url, Constants.db_user, Constants.db_pass);
       
               
                String SQL = ("SELECT  * from møte");      
                int møteId = 0;
                String møteTidspunkt = "";
                String møteSted = "";
                Statement hentmøte = con.createStatement( );
                ResultSet rs = hentmøte.executeQuery (SQL);
                
                    while (rs.next()) {
                      møteId = rs.getInt("møteId");
                      møteTidspunkt = rs.getString("møteTidspunkt");
                      møteSted = rs.getString("møteSted");
                      DML.addElement ("Møte ID:"+ " " +møteId + "   " + "Tidspunkt:" + " " + møteTidspunkt+ "   " + "Sted:" + " "+ møteSted);
                    //  arrayList.add(brukerFornavn + brukerEtternavn);
                }
                jListMøte.setModel(DML);
        
        }
        catch (SQLException err) {
            System.out.println(err);
        }
    }
    private void jButtonModul5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul5ActionPerformed
        // Setter en variabel til et modulnummer, kan nå lage "caser" (eventuelt if/else if) i koden for å laste rett modul.
        setModulTrykket("modul 5");
        moduleInformationWindow modul5 = new moduleInformationWindow();
       modul5.setVisible(true);
    }//GEN-LAST:event_jButtonModul5ActionPerformed

    private void jButtonModul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul3ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 3");
        moduleInformationWindow modul3 = new moduleInformationWindow();
       modul3.setVisible(true);
    }//GEN-LAST:event_jButtonModul3ActionPerformed

    private void jButtonModul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul1ActionPerformed
       setModulTrykket("modul 1");
       moduleInformationWindow modul1 = new moduleInformationWindow();
       modul1.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModul1ActionPerformed

    private void jButtonSendRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendRapportActionPerformed
        // TODO add your handling code here:
        // Setter variablene til queries
        ukeString = jTextFieldUke.getText();
        timerString = jTextFieldTimer.getText();
        // Må gjøre om verdien i tekstfeltene til int før de skal inn i DB
        // Try-catch for å håndtere feil format i feltene
        try {
            uke = Integer.parseInt(ukeString);
        }
        catch (NumberFormatException feilUke){
            System.out.println(feilUke);
        }

        try {
            timer = Integer.parseInt(timerString);
        }
        catch (NumberFormatException feilTimer) {
            System.out.println(feilTimer);
        }
        // Resten av verdiene er tekst også i databasen
        gått = jTextAreaGått.getText();
        annerledes = jTextAreaAnnerledes.getText();
        hjelp = jTextAreaHjelp.getText();

        sendStatusrapport();
        
	jTextFieldUke.setText("");
        jTextAreaGått.setText("");
        jTextAreaAnnerledes.setText("");
        jTextAreaHjelp.setText("");
        jTextFieldTimer.setText("");
        
        JOptionPane.showMessageDialog(null, "<Dine endringer er blitt lagret>", "Alert", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonSendRapportActionPerformed

    private void jButtonModul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul2ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 2");
        moduleInformationWindow modul2 = new moduleInformationWindow();
        modul2.setVisible(true);
        
    }//GEN-LAST:event_jButtonModul2ActionPerformed

    private void jButtonModul4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul4ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 4");
        moduleInformationWindow modul4 = new moduleInformationWindow();
        modul4.setVisible(true);
    }//GEN-LAST:event_jButtonModul4ActionPerformed

    private void jButtonModul6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul6ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 6");
        moduleInformationWindow modul6 = new moduleInformationWindow();
        modul6.setVisible(true);
    }//GEN-LAST:event_jButtonModul6ActionPerformed

    private void jButtonModul7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul7ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 7");
        moduleInformationWindow modul7 = new moduleInformationWindow();
        modul7.setVisible(true);
    }//GEN-LAST:event_jButtonModul7ActionPerformed

    private void jButtonModul8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul8ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 8");
        moduleInformationWindow modul8 = new moduleInformationWindow();
        modul8.setVisible(true);
    }//GEN-LAST:event_jButtonModul8ActionPerformed

    private void jButtonModul9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul9ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 9");
        moduleInformationWindow modul9 = new moduleInformationWindow();
        modul9.setVisible(true);
    }//GEN-LAST:event_jButtonModul9ActionPerformed

    private void jButtonModul10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul10ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 10");
        moduleInformationWindow modul10 = new moduleInformationWindow();
        modul10.setVisible(true);
    }//GEN-LAST:event_jButtonModul10ActionPerformed

    private void jButtonModul11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul11ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 11");
        moduleInformationWindow modul11 = new moduleInformationWindow();
        modul11.setVisible(true);
    }//GEN-LAST:event_jButtonModul11ActionPerformed

    private void jButtonModul12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul12ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 12");
        moduleInformationWindow modul12 = new moduleInformationWindow();
        modul12.setVisible(true);
    }//GEN-LAST:event_jButtonModul12ActionPerformed

    private void jButtonModul13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul13ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 13");
        moduleInformationWindow modul13 = new moduleInformationWindow();
        modul13.setVisible(true);
    }//GEN-LAST:event_jButtonModul13ActionPerformed

    private void jButtonModul14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul14ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 14");
        moduleInformationWindow modul14 = new moduleInformationWindow();
        modul14.setVisible(true);
        
    }//GEN-LAST:event_jButtonModul14ActionPerformed

    private void jTabbedPaneInnleveringerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneInnleveringerMouseClicked
        // henter ut generell info på modul-tab når man klikker på tabbed pane
        
        jTextAreaInfo.setText(getGenerellModul());
    }//GEN-LAST:event_jTabbedPaneInnleveringerMouseClicked

    private void jPanelMøteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMøteMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPanelMøteMouseClicked

    private void testProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testProfilActionPerformed
        // TODO add your handling code here:

        {
    try
        {
    
        
    Class.forName("com.mysql.jdbc.Driver");
    connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/slit","root","root");
    System.out.println("Connection Established Succcesfully...");
    
    JFileChooser chooser=new JFileChooser(new File("E:\\"));
    chooser.setMultiSelectionEnabled(false);
    chooser.setVisible(true);
    chooser.showOpenDialog(this);

    File file=chooser.getSelectedFile();
    if(file!=null){filePath=file.getPath();}


    if(filePath!=null && check())
    {
    ps=connection.prepareStatement("INSERT INTO profilbilde(profilbildeBlob, Bruker_brukerId) VALUES(?,?);");
    FileInputStream fileInputStream=new FileInputStream(filePath);
    byte b[]=new byte[fileInputStream.available()];
    fileInputStream.read(b);
    fileInputStream.close();
    ps.setBytes(1, b);
    ps.setInt(2, slit.Main.user.getId());

    int val=ps.executeUpdate();
    if(val>=1)JOptionPane.showMessageDialog(this, "Din fil ble lastet opp til databasen");
            
    else
    JOptionPane.showMessageDialog(this, "Error");

    }
    else
    {
    JOptionPane.showMessageDialog(this,"Velg riktig filtype");
    }

    }catch(Exception e)
    {

    JOptionPane.showMessageDialog(this, e.getMessage());
    e.printStackTrace();
    }
    }
        displayPhoto();
    }//GEN-LAST:event_testProfilActionPerformed
private boolean check() {
if(filePath!=null)
{
if(filePath.endsWith(".jpeg")||filePath.endsWith(".jpg")||filePath.endsWith(".JPEG")||filePath.endsWith(".docx")||filePath.endsWith(".JPG") || filePath.endsWith(".rar") || filePath.endsWith(".jar") || filePath.endsWith(".zip") || filePath.endsWith(".doc"))
{
return true;
}
return false;
}
return false;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButtonAvbestill;
    private javax.swing.JButton jButtonBestill;
    private javax.swing.JButton jButtonModul1;
    private javax.swing.JButton jButtonModul10;
    private javax.swing.JButton jButtonModul11;
    private javax.swing.JButton jButtonModul12;
    private javax.swing.JButton jButtonModul13;
    private javax.swing.JButton jButtonModul14;
    private javax.swing.JButton jButtonModul2;
    private javax.swing.JButton jButtonModul3;
    private javax.swing.JButton jButtonModul4;
    private javax.swing.JButton jButtonModul5;
    private javax.swing.JButton jButtonModul6;
    private javax.swing.JButton jButtonModul7;
    private javax.swing.JButton jButtonModul8;
    private javax.swing.JButton jButtonModul9;
    private javax.swing.JButton jButtonSendRapport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelModuler109;
    private javax.swing.JLabel jLabelModuler110;
    private javax.swing.JLabel jLabelStatusrapportQuestion1;
    private javax.swing.JLabel jLabelStatusrapportQuestion2;
    private javax.swing.JLabel jLabelStatusrapportQuestion3;
    private javax.swing.JLabel jLabelStatusrapportQuestion4;
    private javax.swing.JLabel jLabelStatusrapportQuestion5;
    private javax.swing.JLabel jLabelTittel;
    private javax.swing.JList jListMøte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBotMain;
    private javax.swing.JPanel jPanelDagensMain;
    private javax.swing.JPanel jPanelHjem;
    private javax.swing.JPanel jPanelLeftCentre;
    private javax.swing.JPanel jPanelLeftLeft;
    private javax.swing.JPanel jPanelLeftMain;
    private javax.swing.JPanel jPanelLeftRight;
    private javax.swing.JPanel jPanelModuler;
    private javax.swing.JPanel jPanelMøte;
    private javax.swing.JPanel jPanelMøteCentre;
    private javax.swing.JPanel jPanelMøteRight;
    private javax.swing.JPanel jPanelMøteTop;
    private javax.swing.JPanel jPanelMøtebot;
    private javax.swing.JPanel jPanelRightMain;
    private javax.swing.JPanel jPanelStatistikk;
    private javax.swing.JPanel jPanelStatistikkMain;
    private javax.swing.JPanel jPanelStatusrapport;
    private javax.swing.JPanel jPanelTopBot;
    private javax.swing.JPanel jPanelTopCentre;
    private javax.swing.JPanel jPanelTopMain;
    private javax.swing.JPanel jPanelTopTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPaneMeny;
    private javax.swing.JScrollPane jScrollPaneModuloversikt;
    private javax.swing.JSeparator jSeperatorLeftLeft;
    private javax.swing.JSeparator jSeperatorLeftRight;
    private javax.swing.JSeparator jSeperatorTopBot;
    private javax.swing.JTabbedPane jTabbedPaneInnleveringer;
    private javax.swing.JTextArea jTextAreaAnnerledes;
    private javax.swing.JTextArea jTextAreaDagens;
    private javax.swing.JTextArea jTextAreaDate;
    private javax.swing.JTextArea jTextAreaGått;
    private javax.swing.JTextArea jTextAreaHjelp;
    private javax.swing.JTextArea jTextAreaId;
    private javax.swing.JTextArea jTextAreaInfo;
    private javax.swing.JTextArea jTextAreaLeverte;
    private javax.swing.JTextArea jTextAreaModulResultat;
    private javax.swing.JTextArea jTextAreaName;
    private javax.swing.JTextArea jTextAreaSurname;
    private javax.swing.JTextField jTextFieldTimer;
    private javax.swing.JTextField jTextFieldUke;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTree jTreeMeny;
    private javax.swing.JPanel mainRight;
    private javax.swing.JLabel profilTitle;
    private javax.swing.JLabel profilbilde;
    private javax.swing.JLabel profilnavnLabel;
    private javax.swing.JLabel profilrolleLabel;
    private javax.swing.JButton testProfil;
    // End of variables declaration//GEN-END:variables
}
