/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slit;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
/**
 *
 * @author Sondre
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */

    private String ukeString = "";
    private String gått = "";
    private String annerledes ="";
    private String hjelp = "";
    private String timerString = "";
    int timer = 0;
    int uke = 0;
    int statusId = 0;
    final static String newline = "\n";
    public mainWindow() {
        initComponents();
        statistikk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanelTopMain = new javax.swing.JPanel();
        jPanelTopCentre = new javax.swing.JPanel();
        jButtonProfil = new javax.swing.JButton();
        jLabelTittel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelTopTop = new javax.swing.JPanel();
        jPanelTopBot = new javax.swing.JPanel();
        jSeperatorTopBot = new javax.swing.JSeparator();
        jPanelLeftMain = new javax.swing.JPanel();
        jPanelLeftLeft = new javax.swing.JPanel();
        jSeperatorLeftLeft = new javax.swing.JSeparator();
        jPanelLeftCentre = new javax.swing.JPanel();
        jScrollPaneMeny = new javax.swing.JScrollPane();
        jTreeMeny = new javax.swing.JTree();
        jPanelLeftRight = new javax.swing.JPanel();
        jSeperatorLeftRight = new javax.swing.JSeparator();
        jPanelLeftRightRight = new javax.swing.JPanel();
        jPanelBotMain = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHjem = new javax.swing.JPanel();
        jPanelModuler = new javax.swing.JPanel();
        jScrollPaneModuloversikt = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabelModuler109 = new javax.swing.JLabel();
        jButtonModul1 = new javax.swing.JButton();
        jButtonModul2 = new javax.swing.JButton();
        jButtonModul3 = new javax.swing.JButton();
        jButtonModul4 = new javax.swing.JButton();
        jButtonModul5 = new javax.swing.JButton();
        jLabelModuler110 = new javax.swing.JLabel();
        jButtonModul6 = new javax.swing.JButton();
        jButtonModul7 = new javax.swing.JButton();
        jButtonModul8 = new javax.swing.JButton();
        jButtonModul9 = new javax.swing.JButton();
        jButtonModul10 = new javax.swing.JButton();
        jButtonModul11 = new javax.swing.JButton();
        jButtonModul12 = new javax.swing.JButton();
        jButtonModul13 = new javax.swing.JButton();
        jButtonModul14 = new javax.swing.JButton();
        jPanelInnlevering = new javax.swing.JPanel();
        jPanelStatistikk = new javax.swing.JPanel();
        jPanelStatistikkMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaId = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaName = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSurname = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDate = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaLeverte = new javax.swing.JTextArea();
        jPanelMøte = new javax.swing.JPanel();
        jButtonBestill = new javax.swing.JButton();
        jButtonAvbestill = new javax.swing.JButton();
        jPanelMøteTop = new javax.swing.JPanel();
        jPanelMøtebot = new javax.swing.JPanel();
        jPanelMøteRight = new javax.swing.JPanel();
        jPanelMøteCentre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelStatusrapport = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion1 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion3 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion5 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaGått = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaHjelp = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextAreaAnnerledes = new javax.swing.JTextArea();
        jButtonSendRapport = new javax.swing.JButton();
        jLabelStatusrapportQuestion2 = new javax.swing.JLabel();
        jPanelRightMain = new javax.swing.JPanel();
        jTextFieldUke = new javax.swing.JTextField();
        jTextFieldTimer = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTopMain.setLayout(new java.awt.BorderLayout());

        jButtonProfil.setText("Profil");

        jLabelTittel.setText("Tittel på systemet IS109-IS110");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slit/UiA logo_middels_None.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelTopCentreLayout = new javax.swing.GroupLayout(jPanelTopCentre);
        jPanelTopCentre.setLayout(jPanelTopCentreLayout);
        jPanelTopCentreLayout.setHorizontalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonProfil)
                        .addContainerGap())
                    .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabelTittel)
                        .addContainerGap(710, Short.MAX_VALUE))))
        );
        jPanelTopCentreLayout.setVerticalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                        .addComponent(jButtonProfil)
                        .addGap(14, 14, 14)
                        .addComponent(jLabelTittel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTopMain.add(jPanelTopCentre, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelTopTopLayout = new javax.swing.GroupLayout(jPanelTopTop);
        jPanelTopTop.setLayout(jPanelTopTopLayout);
        jPanelTopTopLayout.setHorizontalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1387, Short.MAX_VALUE)
        );
        jPanelTopTopLayout.setVerticalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanelTopMain.add(jPanelTopTop, java.awt.BorderLayout.PAGE_START);

        jSeperatorTopBot.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorTopBot.setPreferredSize(new java.awt.Dimension(50, 1));

        javax.swing.GroupLayout jPanelTopBotLayout = new javax.swing.GroupLayout(jPanelTopBot);
        jPanelTopBot.setLayout(jPanelTopBotLayout);
        jPanelTopBotLayout.setHorizontalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1387, Short.MAX_VALUE)
        );
        jPanelTopBotLayout.setVerticalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBotLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanelTopMain.add(jPanelTopBot, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanelTopMain, java.awt.BorderLayout.PAGE_START);

        jPanelLeftLeft.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftLeft.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftLeft.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftLeft.add(jSeperatorLeftLeft, java.awt.BorderLayout.CENTER);

        jPanelLeftCentre.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Hurtignavigering");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Moduler");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Moduloversikt");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduler IS-109");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 1");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 2");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 3");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 4");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduer IS-110");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 6");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 7");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 8");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 9");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 10");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 11");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 12");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 13");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 14");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("osv");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Møte");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Statusrapport");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Hjelp");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("FAQ");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Forum");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("IM");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Om systemet");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeMeny.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeMeny.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPaneMeny.setViewportView(jTreeMeny);

        jPanelLeftCentre.add(jScrollPaneMeny, java.awt.BorderLayout.CENTER);

        jPanelLeftRight.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftRight.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftRight.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftRight.add(jSeperatorLeftRight, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelLeftRightRightLayout = new javax.swing.GroupLayout(jPanelLeftRightRight);
        jPanelLeftRightRight.setLayout(jPanelLeftRightRightLayout);
        jPanelLeftRightRightLayout.setHorizontalGroup(
            jPanelLeftRightRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanelLeftRightRightLayout.setVerticalGroup(
            jPanelLeftRightRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLeftMainLayout = new javax.swing.GroupLayout(jPanelLeftMain);
        jPanelLeftMain.setLayout(jPanelLeftMainLayout);
        jPanelLeftMainLayout.setHorizontalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanelLeftRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanelLeftRightRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLeftMainLayout.setVerticalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
            .addComponent(jPanelLeftRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLeftRightRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLeftMain, java.awt.BorderLayout.LINE_START);
        getContentPane().add(jPanelBotMain, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanelHjemLayout = new javax.swing.GroupLayout(jPanelHjem);
        jPanelHjem.setLayout(jPanelHjemLayout);
        jPanelHjemLayout.setHorizontalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1099, Short.MAX_VALUE)
        );
        jPanelHjemLayout.setVerticalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hjem", jPanelHjem);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Her finner du en oversikt over kursets moduler.\nTrykk deg inn på en modul for å se læringsmål,\nressurser og annen informasjon om modulen du \njobber med.\n\nFor studenter av IS-109 er følgende moduler \nobligatoriske:\n- Modul 1\n- Modul 2\n- Modul 3\n- Modul 4\n\nModul 5 er valgfri i IS-109, men obligatorisk \ni IS-110 om den ikke er gjort.\n\nFor studenter av IS-110 er følgende moduler\nObligatoriske:\n- Modul 5 (om ikke gjort i IS-109)\n- Modul 6\n- Modul 7\n- Modul 8\n- Modul 9\n- Velg minst en av Modul 10,11,12,13 eller 14\n- Oppfordres til å ta så mange som mulig.");
        jTextArea2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneModuloversikt.setViewportView(jTextArea2);

        jLabelModuler109.setText("Moduler IS-109");

        jButtonModul1.setText("Modul 1");
        jButtonModul1.setMaximumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setMinimumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul1ActionPerformed(evt);
            }
        });

        jButtonModul2.setText("Modul 2");
        jButtonModul2.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul3.setText("Modul 3");
        jButtonModul3.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul3ActionPerformed(evt);
            }
        });

        jButtonModul4.setText("Modul 4");
        jButtonModul4.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul5.setText("Modul 5");
        jButtonModul5.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul5ActionPerformed(evt);
            }
        });

        jLabelModuler110.setText("Moduler IS-110");

        jButtonModul6.setText("Modul 6");
        jButtonModul6.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul7.setText("Modul 7");
        jButtonModul7.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul8.setText("Modul 8");
        jButtonModul8.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul9.setText("Modul 9");
        jButtonModul9.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul10.setText("Modul 10");
        jButtonModul10.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul11.setText("Modul 11");
        jButtonModul11.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul12.setText("Modul 12");
        jButtonModul12.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul13.setText("Modul 13");
        jButtonModul13.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul14.setText("Modul 14");
        jButtonModul14.setPreferredSize(new java.awt.Dimension(81, 23));

        javax.swing.GroupLayout jPanelModulerLayout = new javax.swing.GroupLayout(jPanelModuler);
        jPanelModuler.setLayout(jPanelModulerLayout);
        jPanelModulerLayout.setHorizontalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonModul4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabelModuler109, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModul3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModul5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModul6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonModul14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelModuler110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModulerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanelModulerLayout.setVerticalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModuler109)
                            .addComponent(jLabelModuler110))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Moduler", jPanelModuler);

        javax.swing.GroupLayout jPanelInnleveringLayout = new javax.swing.GroupLayout(jPanelInnlevering);
        jPanelInnlevering.setLayout(jPanelInnleveringLayout);
        jPanelInnleveringLayout.setHorizontalGroup(
            jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1099, Short.MAX_VALUE)
        );
        jPanelInnleveringLayout.setVerticalGroup(
            jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Innlevering", jPanelInnlevering);

        jPanelStatistikk.setLayout(new java.awt.BorderLayout());

        jPanelStatistikkMain.setLayout(new javax.swing.BoxLayout(jPanelStatistikkMain, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaId.setColumns(20);
        jTextAreaId.setRows(5);
        jScrollPane2.setViewportView(jTextAreaId);

        jPanelStatistikkMain.add(jScrollPane2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaName.setColumns(20);
        jTextAreaName.setRows(5);
        jScrollPane3.setViewportView(jTextAreaName);

        jPanelStatistikkMain.add(jScrollPane3);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaSurname.setColumns(20);
        jTextAreaSurname.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSurname);

        jPanelStatistikkMain.add(jScrollPane4);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaDate.setColumns(20);
        jTextAreaDate.setRows(5);
        jScrollPane5.setViewportView(jTextAreaDate);

        jPanelStatistikkMain.add(jScrollPane5);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaLeverte.setColumns(20);
        jTextAreaLeverte.setRows(5);
        jScrollPane6.setViewportView(jTextAreaLeverte);

        jPanelStatistikkMain.add(jScrollPane6);

        jPanelStatistikk.add(jPanelStatistikkMain, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Statistikk", jPanelStatistikk);

        jButtonBestill.setText("Bestill møte");
        jPanelMøte.add(jButtonBestill);

        jButtonAvbestill.setText("Avbestill møte");
        jPanelMøte.add(jButtonAvbestill);

        jPanelMøteTop.setLayout(new javax.swing.BoxLayout(jPanelMøteTop, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMøte.add(jPanelMøteTop);

        jPanelMøtebot.setLayout(new javax.swing.BoxLayout(jPanelMøtebot, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMøte.add(jPanelMøtebot);

        jPanelMøteRight.setLayout(new javax.swing.BoxLayout(jPanelMøteRight, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMøte.add(jPanelMøteRight);

        jPanelMøteCentre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Møteplan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanelMøteCentre.setLayout(new javax.swing.BoxLayout(jPanelMøteCentre, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelMøteCentre.add(jScrollPane1);

        jPanelMøte.add(jPanelMøteCentre);

        jTabbedPane1.addTab("Møte", jPanelMøte);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Statusrapport:");

        jLabelStatusrapportQuestion1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion1.setText("Hvilken uke rapporterer du for?");

        jLabelStatusrapportQuestion3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion3.setText("Hva kunne blitt gjort annerledes?");

        jLabelStatusrapportQuestion5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion5.setText("Hvor mange timer har du jobbet denne uken?");

        jLabelStatusrapportQuestion4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion4.setText("Spesielle problemer eller ønske om forelesningstema?");

        jTextAreaGått.setColumns(20);
        jTextAreaGått.setRows(5);
        jScrollPane7.setViewportView(jTextAreaGått);

        jTextAreaHjelp.setColumns(20);
        jTextAreaHjelp.setRows(5);
        jScrollPane8.setViewportView(jTextAreaHjelp);

        jTextAreaAnnerledes.setColumns(20);
        jTextAreaAnnerledes.setRows(5);
        jScrollPane10.setViewportView(jTextAreaAnnerledes);

        jButtonSendRapport.setText("Send/lagre");
        jButtonSendRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendRapportActionPerformed(evt);
            }
        });

        jLabelStatusrapportQuestion2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion2.setText("Hvordan har det gått?");

        javax.swing.GroupLayout jPanelRightMainLayout = new javax.swing.GroupLayout(jPanelRightMain);
        jPanelRightMain.setLayout(jPanelRightMainLayout);
        jPanelRightMainLayout.setHorizontalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelRightMainLayout.setVerticalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelStatusrapportLayout = new javax.swing.GroupLayout(jPanelStatusrapport);
        jPanelStatusrapport.setLayout(jPanelStatusrapportLayout);
        jPanelStatusrapportLayout.setHorizontalGroup(
            jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusrapportLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelStatusrapportQuestion1)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(jLabelStatusrapportQuestion5)
                        .addComponent(jLabelStatusrapportQuestion2)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(jLabelStatusrapportQuestion3)
                        .addComponent(jLabelStatusrapportQuestion4)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(jTextFieldUke)
                        .addComponent(jTextFieldTimer))
                    .addComponent(jButtonSendRapport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                .addComponent(jPanelRightMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelStatusrapportLayout.setVerticalGroup(
            jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelStatusrapportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStatusrapportQuestion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabelStatusrapportQuestion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabelStatusrapportQuestion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatusrapportQuestion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatusrapportQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSendRapport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelStatusrapportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelRightMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Statusrapport", jPanelStatusrapport);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void statistikk () {
    
        try {
   
            System.out.println("The URL is: " + Constants.db_url);
            Connection con = DriverManager.getConnection(Constants.db_url, Constants.db_user, Constants.db_pass);
            
            Statement stmt = con.createStatement( );
            
            String SQL ="SELECT * FROM Statistikk";
            ResultSet result = stmt.executeQuery (SQL);
            int id_col = 0;
            String name = "";
            String surname = "";
            String dato = "";
            int antLeverte =0;
            while (result.next() ) {
                id_col = result.getInt("Bruker_brukerId");
                name = result.getString("brukerFornavn");
                surname = result.getString("brukerEtternavn");
                dato = result.getString("levertmodulDato");
                antLeverte = result.getInt("COUNT(sensurId)");    
                jTextAreaId.append(" " + "Bruker ID:"+ " " + id_col + newline);
                jTextAreaName.append(" " + "Fornavn:" + " " + name + newline);
                jTextAreaSurname.append(" " + "Etternavn:" + " " + surname + newline);
                jTextAreaDate.append(" " + "Aktivitet:" + " " + dato + newline);
                jTextAreaLeverte.append(" " + "Moduler med sensur:" + " " + antLeverte + newline);
            }
          
        }
        catch (SQLException SQLstatistikkfeil) {
            System.out.println(SQLstatistikkfeil);
            
        }
        
        
    }
        
    
          
            
   
    private void sendStatusrapport() {
        if (Main.user != null)
        db.sendRapport(uke, gått, annerledes, hjelp, timer);
              
    }
    private void jButtonModul5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModul5ActionPerformed

    private void jButtonModul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModul3ActionPerformed

    private void jButtonModul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul1ActionPerformed
    
    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModul1ActionPerformed

    private void jButtonSendRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendRapportActionPerformed
        // TODO add your handling code here:
        // Setter variablene til queries
        ukeString = jTextFieldUke.getText();
        timerString = jTextFieldTimer.getText();
        // Må gjøre om verdien i tekstfeltene til int før de skal inn i DB
        // Try-catch for å håndtere feil format i feltene
        try {
            uke = Integer.parseInt(ukeString);
        }
        catch (NumberFormatException feilUke){
            System.out.println(feilUke);
        }

        try {
            timer = Integer.parseInt(timerString);
        }
        catch (NumberFormatException feilTimer) {
            System.out.println(feilTimer);
        }
        // Resten av verdiene er tekst også i databasen
        gått = jTextAreaGått.getText();
        annerledes = jTextAreaAnnerledes.getText();
        hjelp = jTextAreaHjelp.getText();
   
        sendStatusrapport();

    }//GEN-LAST:event_jButtonSendRapportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvbestill;
    private javax.swing.JButton jButtonBestill;
    private javax.swing.JButton jButtonModul1;
    private javax.swing.JButton jButtonModul10;
    private javax.swing.JButton jButtonModul11;
    private javax.swing.JButton jButtonModul12;
    private javax.swing.JButton jButtonModul13;
    private javax.swing.JButton jButtonModul14;
    private javax.swing.JButton jButtonModul2;
    private javax.swing.JButton jButtonModul3;
    private javax.swing.JButton jButtonModul4;
    private javax.swing.JButton jButtonModul5;
    private javax.swing.JButton jButtonModul6;
    private javax.swing.JButton jButtonModul7;
    private javax.swing.JButton jButtonModul8;
    private javax.swing.JButton jButtonModul9;
    private javax.swing.JButton jButtonProfil;
    private javax.swing.JButton jButtonSendRapport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelModuler109;
    private javax.swing.JLabel jLabelModuler110;
    private javax.swing.JLabel jLabelStatusrapportQuestion1;
    private javax.swing.JLabel jLabelStatusrapportQuestion2;
    private javax.swing.JLabel jLabelStatusrapportQuestion3;
    private javax.swing.JLabel jLabelStatusrapportQuestion4;
    private javax.swing.JLabel jLabelStatusrapportQuestion5;
    private javax.swing.JLabel jLabelTittel;
    private javax.swing.JPanel jPanelBotMain;
    private javax.swing.JPanel jPanelHjem;
    private javax.swing.JPanel jPanelInnlevering;
    private javax.swing.JPanel jPanelLeftCentre;
    private javax.swing.JPanel jPanelLeftLeft;
    private javax.swing.JPanel jPanelLeftMain;
    private javax.swing.JPanel jPanelLeftRight;
    private javax.swing.JPanel jPanelLeftRightRight;
    private javax.swing.JPanel jPanelModuler;
    private javax.swing.JPanel jPanelMøte;
    private javax.swing.JPanel jPanelMøteCentre;
    private javax.swing.JPanel jPanelMøteRight;
    private javax.swing.JPanel jPanelMøteTop;
    private javax.swing.JPanel jPanelMøtebot;
    private javax.swing.JPanel jPanelRightMain;
    private javax.swing.JPanel jPanelStatistikk;
    private javax.swing.JPanel jPanelStatistikkMain;
    private javax.swing.JPanel jPanelStatusrapport;
    private javax.swing.JPanel jPanelTopBot;
    private javax.swing.JPanel jPanelTopCentre;
    private javax.swing.JPanel jPanelTopMain;
    private javax.swing.JPanel jPanelTopTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPaneMeny;
    private javax.swing.JScrollPane jScrollPaneModuloversikt;
    private javax.swing.JSeparator jSeperatorLeftLeft;
    private javax.swing.JSeparator jSeperatorLeftRight;
    private javax.swing.JSeparator jSeperatorTopBot;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaAnnerledes;
    private javax.swing.JTextArea jTextAreaDate;
    private javax.swing.JTextArea jTextAreaGått;
    private javax.swing.JTextArea jTextAreaHjelp;
    private javax.swing.JTextArea jTextAreaId;
    private javax.swing.JTextArea jTextAreaLeverte;
    private javax.swing.JTextArea jTextAreaName;
    private javax.swing.JTextArea jTextAreaSurname;
    private javax.swing.JTextField jTextFieldTimer;
    private javax.swing.JTextField jTextFieldUke;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTree jTreeMeny;
    // End of variables declaration//GEN-END:variables
}
