/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slit;

/**
 *
 * @author Sondre
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTopMain = new javax.swing.JPanel();
        jPanelTopCentre = new javax.swing.JPanel();
        jButtonProfil = new javax.swing.JButton();
        jLabelTittel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelTopTop = new javax.swing.JPanel();
        jPanelTopBot = new javax.swing.JPanel();
        jSeperatorTopBot = new javax.swing.JSeparator();
        jPanelLeftMain = new javax.swing.JPanel();
        jPanelLeftLeft = new javax.swing.JPanel();
        jSeperatorLeftLeft = new javax.swing.JSeparator();
        jPanelLeftCentre = new javax.swing.JPanel();
        jScrollPaneMeny = new javax.swing.JScrollPane();
        jTreeMeny = new javax.swing.JTree();
        jPanelLeftRight = new javax.swing.JPanel();
        jSeperatorLeftRight = new javax.swing.JSeparator();
        jPanelLeftRightRight = new javax.swing.JPanel();
        jPanelBotMain = new javax.swing.JPanel();
        jPanelRightMain = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHjem = new javax.swing.JPanel();
        jPanelModuler = new javax.swing.JPanel();
        jScrollPaneModuloversikt = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabelModuler109 = new javax.swing.JLabel();
        jButtonModul1 = new javax.swing.JButton();
        jButtonModul2 = new javax.swing.JButton();
        jButtonModul3 = new javax.swing.JButton();
        jButtonModul4 = new javax.swing.JButton();
        jButtonModul5 = new javax.swing.JButton();
        jLabelModuler110 = new javax.swing.JLabel();
        jButtonModul6 = new javax.swing.JButton();
        jButtonModul7 = new javax.swing.JButton();
        jButtonModul8 = new javax.swing.JButton();
        jButtonModul9 = new javax.swing.JButton();
        jButtonModul10 = new javax.swing.JButton();
        jButtonModul11 = new javax.swing.JButton();
        jButtonModul12 = new javax.swing.JButton();
        jButtonModul13 = new javax.swing.JButton();
        jButtonModul14 = new javax.swing.JButton();
        jPanelInnlevering = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jPanelMøte = new javax.swing.JPanel();
        jPanelStatusrapport = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelQuestion1Statusrapp = new javax.swing.JLabel();
        ModulValg = new javax.swing.JComboBox();
        jLabelQuestion2Statusrapp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAnswerQuestion2 = new javax.swing.JTextArea();
        jLabelQuestion3Statusrapp = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAnswerQuestion3 = new javax.swing.JTextArea();
        jLabelQuestion4Statusrapp = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaAnswerQuestion4 = new javax.swing.JTextArea();
        jLabelQuestion5Statusrapp = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaAnswerQuestion5 = new javax.swing.JTextArea();
        jButtonLagre = new javax.swing.JButton();
        jLabelStatusrapport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTopMain.setLayout(new java.awt.BorderLayout());

        jButtonProfil.setText("Profil");

        jLabelTittel.setText("Tittel på systemet IS109-IS110");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slit/UiA logo_middels_None.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelTopCentreLayout = new javax.swing.GroupLayout(jPanelTopCentre);
        jPanelTopCentre.setLayout(jPanelTopCentreLayout);
        jPanelTopCentreLayout.setHorizontalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonProfil)
                        .addContainerGap())
                    .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabelTittel)
                        .addContainerGap(869, Short.MAX_VALUE))))
        );
        jPanelTopCentreLayout.setVerticalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                        .addComponent(jButtonProfil)
                        .addGap(14, 14, 14)
                        .addComponent(jLabelTittel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTopMain.add(jPanelTopCentre, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelTopTopLayout = new javax.swing.GroupLayout(jPanelTopTop);
        jPanelTopTop.setLayout(jPanelTopTopLayout);
        jPanelTopTopLayout.setHorizontalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1546, Short.MAX_VALUE)
        );
        jPanelTopTopLayout.setVerticalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanelTopMain.add(jPanelTopTop, java.awt.BorderLayout.PAGE_START);

        jSeperatorTopBot.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorTopBot.setPreferredSize(new java.awt.Dimension(50, 1));

        javax.swing.GroupLayout jPanelTopBotLayout = new javax.swing.GroupLayout(jPanelTopBot);
        jPanelTopBot.setLayout(jPanelTopBotLayout);
        jPanelTopBotLayout.setHorizontalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1546, Short.MAX_VALUE)
        );
        jPanelTopBotLayout.setVerticalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBotLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanelTopMain.add(jPanelTopBot, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanelTopMain, java.awt.BorderLayout.PAGE_START);

        jPanelLeftLeft.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftLeft.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftLeft.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftLeft.add(jSeperatorLeftLeft, java.awt.BorderLayout.CENTER);

        jPanelLeftCentre.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Hurtignavigering");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Moduler");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Moduloversikt");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduler IS-109");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 1");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 2");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 3");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 4");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduer IS-110");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 6");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 7");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 8");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 9");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 10");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 11");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 12");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 13");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 14");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("osv");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Møte");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Statusrapport");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Hjelp");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("FAQ");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Forum");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("IM");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Om systemet");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeMeny.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeMeny.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPaneMeny.setViewportView(jTreeMeny);

        jPanelLeftCentre.add(jScrollPaneMeny, java.awt.BorderLayout.CENTER);

        jPanelLeftRight.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftRight.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftRight.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftRight.add(jSeperatorLeftRight, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelLeftRightRightLayout = new javax.swing.GroupLayout(jPanelLeftRightRight);
        jPanelLeftRightRight.setLayout(jPanelLeftRightRightLayout);
        jPanelLeftRightRightLayout.setHorizontalGroup(
            jPanelLeftRightRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanelLeftRightRightLayout.setVerticalGroup(
            jPanelLeftRightRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLeftMainLayout = new javax.swing.GroupLayout(jPanelLeftMain);
        jPanelLeftMain.setLayout(jPanelLeftMainLayout);
        jPanelLeftMainLayout.setHorizontalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanelLeftRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanelLeftRightRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLeftMainLayout.setVerticalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
            .addComponent(jPanelLeftRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLeftRightRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLeftMain, java.awt.BorderLayout.LINE_START);
        getContentPane().add(jPanelBotMain, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanelRightMainLayout = new javax.swing.GroupLayout(jPanelRightMain);
        jPanelRightMain.setLayout(jPanelRightMainLayout);
        jPanelRightMainLayout.setHorizontalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelRightMainLayout.setVerticalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelRightMain, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanelHjemLayout = new javax.swing.GroupLayout(jPanelHjem);
        jPanelHjem.setLayout(jPanelHjemLayout);
        jPanelHjemLayout.setHorizontalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        jPanelHjemLayout.setVerticalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hjem", jPanelHjem);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Her finner du en oversikt over kursets moduler.\nTrykk deg inn på en modul for å se læringsmål,\nressurser og annen informasjon om modulen du \njobber med.\n\nFor studenter av IS-109 er følgende moduler \nobligatoriske:\n- Modul 1\n- Modul 2\n- Modul 3\n- Modul 4\n\nModul 5 er valgfri i IS-109, men obligatorisk \ni IS-110 om den ikke er gjort.\n\nFor studenter av IS-110 er følgende moduler\nObligatoriske:\n- Modul 5 (om ikke gjort i IS-109)\n- Modul 6\n- Modul 7\n- Modul 8\n- Modul 9\n- Velg minst en av Modul 10,11,12,13 eller 14\n- Oppfordres til å ta så mange som mulig.");
        jTextArea2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneModuloversikt.setViewportView(jTextArea2);

        jLabelModuler109.setText("Moduler IS-109");

        jButtonModul1.setText("Modul 1");
        jButtonModul1.setMaximumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setMinimumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul1ActionPerformed(evt);
            }
        });

        jButtonModul2.setText("Modul 2");
        jButtonModul2.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul3.setText("Modul 3");
        jButtonModul3.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul3ActionPerformed(evt);
            }
        });

        jButtonModul4.setText("Modul 4");
        jButtonModul4.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul5.setText("Modul 5");
        jButtonModul5.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul5ActionPerformed(evt);
            }
        });

        jLabelModuler110.setText("Moduler IS-110");

        jButtonModul6.setText("Modul 6");
        jButtonModul6.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul7.setText("Modul 7");
        jButtonModul7.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul8.setText("Modul 8");
        jButtonModul8.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul9.setText("Modul 9");
        jButtonModul9.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul10.setText("Modul 10");
        jButtonModul10.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul11.setText("Modul 11");
        jButtonModul11.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul12.setText("Modul 12");
        jButtonModul12.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul13.setText("Modul 13");
        jButtonModul13.setPreferredSize(new java.awt.Dimension(81, 23));

        jButtonModul14.setText("Modul 14");
        jButtonModul14.setPreferredSize(new java.awt.Dimension(81, 23));

        javax.swing.GroupLayout jPanelModulerLayout = new javax.swing.GroupLayout(jPanelModuler);
        jPanelModuler.setLayout(jPanelModulerLayout);
        jPanelModulerLayout.setHorizontalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonModul4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabelModuler109, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModul3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModul5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModul6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonModul14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelModuler110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModulerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanelModulerLayout.setVerticalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModuler109)
                            .addComponent(jLabelModuler110))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Moduler", jPanelModuler);

        jList1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jList1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 0, 204));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Innlevering modul 1", "", "Innlevering modul 2", "", "Innlevering modul 3", "", "Innlevering modul 4", "", "Innlevering modul 5", "", "Innlevering modul 6", "", "Innlevering modul 7", "", "Innlevering modul 8", "", "Innlevering modul 9", "", "Innlevering modul 10", "", "Innlevering modul 11", "", "Innlevering modul 12", "", "Innlevering modul 13", "", "Innlevering modul 14" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("");
        jScrollPane2.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Modul innleveringer:");

        javax.swing.GroupLayout jPanelInnleveringLayout = new javax.swing.GroupLayout(jPanelInnlevering);
        jPanelInnlevering.setLayout(jPanelInnleveringLayout);
        jPanelInnleveringLayout.setHorizontalGroup(
            jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInnleveringLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        jPanelInnleveringLayout.setVerticalGroup(
            jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInnleveringLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Innlevering", jPanelInnlevering);

        javax.swing.GroupLayout jPanelMøteLayout = new javax.swing.GroupLayout(jPanelMøte);
        jPanelMøte.setLayout(jPanelMøteLayout);
        jPanelMøteLayout.setHorizontalGroup(
            jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        jPanelMøteLayout.setVerticalGroup(
            jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Møte", jPanelMøte);

        jPanelStatusrapport.setLayout(new javax.swing.BoxLayout(jPanelStatusrapport, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.setToolTipText("Statusrapport");

        jLabelQuestion1Statusrapp.setText("Hvilken modul jobber du med?");

        ModulValg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Modul 1", "Modul 2", "Modul 3", "Modul 4 ", "Modul 5", "Modul 6 ", "Modul 7", "Modul 8", "Modul 9", "Modul 10" }));

        jLabelQuestion2Statusrapp.setText("Hva har du jobbet med denne uken?");

        jTextAreaAnswerQuestion2.setColumns(20);
        jTextAreaAnswerQuestion2.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAnswerQuestion2);

        jLabelQuestion3Statusrapp.setText("Hva har du lært denne uken?");

        jTextAreaAnswerQuestion3.setColumns(20);
        jTextAreaAnswerQuestion3.setRows(5);
        jScrollPane3.setViewportView(jTextAreaAnswerQuestion3);

        jLabelQuestion4Statusrapp.setText("Er det noe du har hatt problemer med?");

        jTextAreaAnswerQuestion4.setColumns(20);
        jTextAreaAnswerQuestion4.setRows(5);
        jScrollPane4.setViewportView(jTextAreaAnswerQuestion4);

        jLabelQuestion5Statusrapp.setText("Har du et tema du ønsker å gå igjennom på forelesning?");

        jTextAreaAnswerQuestion5.setColumns(20);
        jTextAreaAnswerQuestion5.setRows(5);
        jScrollPane5.setViewportView(jTextAreaAnswerQuestion5);

        jButtonLagre.setText("Lagre/Send");

        jLabelStatusrapport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStatusrapport.setText("Statusrapport");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonLagre)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(ModulValg, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelQuestion2Statusrapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelQuestion1Statusrapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelQuestion4Statusrapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelQuestion5Statusrapp, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                            .addComponent(jLabelQuestion3Statusrapp)
                            .addComponent(jLabelStatusrapport, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4)))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addContainerGap(514, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStatusrapport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelQuestion1Statusrapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModulValg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelQuestion2Statusrapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelQuestion3Statusrapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelQuestion4Statusrapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelQuestion5Statusrapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLagre)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jPanelStatusrapport.add(jPanel2);

        jTabbedPane1.addTab("Statusrapport", jPanelStatusrapport);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModul5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModul5ActionPerformed

    private void jButtonModul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModul3ActionPerformed

    private void jButtonModul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul1ActionPerformed
    
    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModul1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ModulValg;
    private javax.swing.JButton jButtonLagre;
    private javax.swing.JButton jButtonModul1;
    private javax.swing.JButton jButtonModul10;
    private javax.swing.JButton jButtonModul11;
    private javax.swing.JButton jButtonModul12;
    private javax.swing.JButton jButtonModul13;
    private javax.swing.JButton jButtonModul14;
    private javax.swing.JButton jButtonModul2;
    private javax.swing.JButton jButtonModul3;
    private javax.swing.JButton jButtonModul4;
    private javax.swing.JButton jButtonModul5;
    private javax.swing.JButton jButtonModul6;
    private javax.swing.JButton jButtonModul7;
    private javax.swing.JButton jButtonModul8;
    private javax.swing.JButton jButtonModul9;
    private javax.swing.JButton jButtonProfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelModuler109;
    private javax.swing.JLabel jLabelModuler110;
    private javax.swing.JLabel jLabelQuestion1Statusrapp;
    private javax.swing.JLabel jLabelQuestion2Statusrapp;
    private javax.swing.JLabel jLabelQuestion3Statusrapp;
    private javax.swing.JLabel jLabelQuestion4Statusrapp;
    private javax.swing.JLabel jLabelQuestion5Statusrapp;
    private javax.swing.JLabel jLabelStatusrapport;
    private javax.swing.JLabel jLabelTittel;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBotMain;
    private javax.swing.JPanel jPanelHjem;
    private javax.swing.JPanel jPanelInnlevering;
    private javax.swing.JPanel jPanelLeftCentre;
    private javax.swing.JPanel jPanelLeftLeft;
    private javax.swing.JPanel jPanelLeftMain;
    private javax.swing.JPanel jPanelLeftRight;
    private javax.swing.JPanel jPanelLeftRightRight;
    private javax.swing.JPanel jPanelModuler;
    private javax.swing.JPanel jPanelMøte;
    private javax.swing.JPanel jPanelRightMain;
    private javax.swing.JPanel jPanelStatusrapport;
    private javax.swing.JPanel jPanelTopBot;
    private javax.swing.JPanel jPanelTopCentre;
    private javax.swing.JPanel jPanelTopMain;
    private javax.swing.JPanel jPanelTopTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPaneMeny;
    private javax.swing.JScrollPane jScrollPaneModuloversikt;
    private javax.swing.JSeparator jSeperatorLeftLeft;
    private javax.swing.JSeparator jSeperatorLeftRight;
    private javax.swing.JSeparator jSeperatorTopBot;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaAnswerQuestion2;
    private javax.swing.JTextArea jTextAreaAnswerQuestion3;
    private javax.swing.JTextArea jTextAreaAnswerQuestion4;
    private javax.swing.JTextArea jTextAreaAnswerQuestion5;
    private javax.swing.JTree jTreeMeny;
    // End of variables declaration//GEN-END:variables
}
