/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slit.client.foreleser;

import slit.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import slit.client.foreleser.moduleInformationWindowForeleser;
import javax.swing.JOptionPane;
/**
 *
 * @author Sondre
 */
public class mainWindowForeleser extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
   
   // ArrayList<String> arrayList = new ArrayList<String>(); 
   private static String modulTrykket = "";
   private static String generellModul = "";
   private static String valgtBruker = "";
   private static String brukerNavn = "";

    public static String getBrukerNavn() {
        return brukerNavn;
    }

    public static void setBrukerNavn(String brukerNavn) {
        mainWindowForeleser.brukerNavn = brukerNavn;
    }

    public static String getValgtBruker() {
        return valgtBruker;
    }

    public static void setValgtBruker(String valgtBruker) {
        mainWindowForeleser.valgtBruker = valgtBruker;
    }
    public static String getGenerellModul () {
        return generellModul;
    }
    public void setGenerellModul(String generellModul) {
        this.generellModul = generellModul;       
    }
    public static String getModulTrykket() {
        return modulTrykket;
    }

    public  void setModulTrykket(String modulTrykket) {
        this.modulTrykket = modulTrykket;
    }
    final static String newline = "\n";
    public mainWindowForeleser() {  
        initComponents();
        statistikkVisning();
        profilVisning ();
        hentBrukere();
        
        
        
    }
    
    private String user = "";
    private String pass ="";
    private String tidspunkt = "";
    private String møtested ="";
    private String tidspunktString = "";
    private int id = 0;
    private String idString = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanelTopMain = new javax.swing.JPanel();
        jPanelTopCentre = new javax.swing.JPanel();
        jLabelTittel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelTopTop = new javax.swing.JPanel();
        jPanelTopBot = new javax.swing.JPanel();
        jSeperatorTopBot = new javax.swing.JSeparator();
        jPanelLeftMain = new javax.swing.JPanel();
        jPanelLeftLeft = new javax.swing.JPanel();
        jSeperatorLeftLeft = new javax.swing.JSeparator();
        jPanelLeftCentre = new javax.swing.JPanel();
        jScrollPaneMeny = new javax.swing.JScrollPane();
        jTreeMeny = new javax.swing.JTree();
        jPanelLeftRight = new javax.swing.JPanel();
        jSeperatorLeftRight = new javax.swing.JSeparator();
        jPanelLeftRightRight = new javax.swing.JPanel();
        jPanelBotMain = new javax.swing.JPanel();
        jPanelRightMain = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextAreaProfil = new javax.swing.JTextArea();
        profilTitle = new javax.swing.JLabel();
        profilUpload = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHjem = new javax.swing.JPanel();
        jPanelModuler = new javax.swing.JPanel();
        jScrollPaneModuloversikt = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jLabelModuler109 = new javax.swing.JLabel();
        jButtonModul1 = new javax.swing.JButton();
        jButtonModul2 = new javax.swing.JButton();
        jButtonModul3 = new javax.swing.JButton();
        jButtonModul4 = new javax.swing.JButton();
        jButtonModul5 = new javax.swing.JButton();
        jLabelModuler110 = new javax.swing.JLabel();
        jButtonModul6 = new javax.swing.JButton();
        jButtonModul7 = new javax.swing.JButton();
        jButtonModul8 = new javax.swing.JButton();
        jButtonModul9 = new javax.swing.JButton();
        jButtonModul10 = new javax.swing.JButton();
        jButtonModul11 = new javax.swing.JButton();
        jButtonModul12 = new javax.swing.JButton();
        jButtonModul13 = new javax.swing.JButton();
        jButtonModul14 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonLagreInfo = new javax.swing.JButton();
        jPanelInnlevering = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jPanelStatistikk = new javax.swing.JPanel();
        jPanelStatistikkMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaId = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaName = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSurname = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDate = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaLeverte = new javax.swing.JTextArea();
        jPanelStatusrapport = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion1 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion3 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion5 = new javax.swing.JLabel();
        jLabelStatusrapportQuestion4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButtonSendRapport = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabelStatusrapportQuestion2 = new javax.swing.JLabel();
        jPanelMøte = new javax.swing.JPanel();
        jPanelMøteLeft = new javax.swing.JPanel();
        jTextFieldDeltaker = new javax.swing.JTextField();
        jLabelMøtedeltaker = new javax.swing.JLabel();
        jLabelTidspunkt = new javax.swing.JLabel();
        jTextFieldTidspunkt = new javax.swing.JTextField();
        jLabelSted = new javax.swing.JLabel();
        jTextFieldSted = new javax.swing.JTextField();
        jButtonLagre = new javax.swing.JButton();
        jButtonSlett = new javax.swing.JButton();
        jPanelMøteTop = new javax.swing.JPanel();
        jPanelMøtebot = new javax.swing.JPanel();
        jPanelMøteRight = new javax.swing.JPanel();
        jPanelMøteCentre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTopMain.setLayout(new java.awt.BorderLayout());

        jLabelTittel.setText("Tittel på systemet IS109-IS110");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slit/UiA logo_middels_None.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelTopCentreLayout = new javax.swing.GroupLayout(jPanelTopCentre);
        jPanelTopCentre.setLayout(jPanelTopCentreLayout);
        jPanelTopCentreLayout.setHorizontalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(116, 116, 116)
                .addComponent(jLabelTittel)
                .addContainerGap(726, Short.MAX_VALUE))
        );
        jPanelTopCentreLayout.setVerticalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabelTittel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTopMain.add(jPanelTopCentre, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelTopTopLayout = new javax.swing.GroupLayout(jPanelTopTop);
        jPanelTopTop.setLayout(jPanelTopTopLayout);
        jPanelTopTopLayout.setHorizontalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1403, Short.MAX_VALUE)
        );
        jPanelTopTopLayout.setVerticalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanelTopMain.add(jPanelTopTop, java.awt.BorderLayout.PAGE_START);

        jSeperatorTopBot.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorTopBot.setPreferredSize(new java.awt.Dimension(50, 1));

        javax.swing.GroupLayout jPanelTopBotLayout = new javax.swing.GroupLayout(jPanelTopBot);
        jPanelTopBot.setLayout(jPanelTopBotLayout);
        jPanelTopBotLayout.setHorizontalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1403, Short.MAX_VALUE)
        );
        jPanelTopBotLayout.setVerticalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBotLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanelTopMain.add(jPanelTopBot, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanelTopMain, java.awt.BorderLayout.PAGE_START);

        jPanelLeftLeft.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftLeft.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftLeft.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftLeft.add(jSeperatorLeftLeft, java.awt.BorderLayout.CENTER);

        jPanelLeftCentre.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Hurtignavigering");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Moduler");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Moduloversikt");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduler IS-109");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 1");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 2");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 3");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 4");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduer IS-110");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 6");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 7");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 8");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 9");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 10");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 11");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 12");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 13");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 14");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("osv");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Møte");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Statusrapport");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Hjelp");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("FAQ");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Forum");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("IM");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Om systemet");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeMeny.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeMeny.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPaneMeny.setViewportView(jTreeMeny);

        jPanelLeftCentre.add(jScrollPaneMeny, java.awt.BorderLayout.CENTER);

        jPanelLeftRight.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftRight.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftRight.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftRight.add(jSeperatorLeftRight, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelLeftRightRightLayout = new javax.swing.GroupLayout(jPanelLeftRightRight);
        jPanelLeftRightRight.setLayout(jPanelLeftRightRightLayout);
        jPanelLeftRightRightLayout.setHorizontalGroup(
            jPanelLeftRightRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanelLeftRightRightLayout.setVerticalGroup(
            jPanelLeftRightRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLeftMainLayout = new javax.swing.GroupLayout(jPanelLeftMain);
        jPanelLeftMain.setLayout(jPanelLeftMainLayout);
        jPanelLeftMainLayout.setHorizontalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanelLeftRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanelLeftRightRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLeftMainLayout.setVerticalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
            .addComponent(jPanelLeftRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLeftRightRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLeftMain, java.awt.BorderLayout.LINE_START);
        getContentPane().add(jPanelBotMain, java.awt.BorderLayout.PAGE_END);

        jTextAreaProfil.setEditable(false);
        jTextAreaProfil.setColumns(20);
        jTextAreaProfil.setRows(5);
        jScrollPane13.setViewportView(jTextAreaProfil);

        profilTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        profilTitle.setForeground(new java.awt.Color(0, 0, 204));
        profilTitle.setText("Profil");

        profilUpload.setText("Upload");
        profilUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRightMainLayout = new javax.swing.GroupLayout(jPanelRightMain);
        jPanelRightMain.setLayout(jPanelRightMainLayout);
        jPanelRightMainLayout.setHorizontalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRightMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(profilUpload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRightMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRightMainLayout.setVerticalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightMainLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(profilTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profilUpload)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelRightMain, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelHjemLayout = new javax.swing.GroupLayout(jPanelHjem);
        jPanelHjem.setLayout(jPanelHjemLayout);
        jPanelHjemLayout.setHorizontalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        jPanelHjemLayout.setVerticalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hjem", jPanelHjem);

        jTextAreaInfo.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaInfo.setColumns(20);
        jTextAreaInfo.setRows(5);
        jTextAreaInfo.setText("\n");
        jTextAreaInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneModuloversikt.setViewportView(jTextAreaInfo);

        jLabelModuler109.setText("Moduler IS-109");

        jButtonModul1.setText("Modul 1");
        jButtonModul1.setMaximumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setMinimumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul1ActionPerformed(evt);
            }
        });

        jButtonModul2.setText("Modul 2");
        jButtonModul2.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul2ActionPerformed(evt);
            }
        });

        jButtonModul3.setText("Modul 3");
        jButtonModul3.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul3ActionPerformed(evt);
            }
        });

        jButtonModul4.setText("Modul 4");
        jButtonModul4.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul4ActionPerformed(evt);
            }
        });

        jButtonModul5.setText("Modul 5");
        jButtonModul5.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul5ActionPerformed(evt);
            }
        });

        jLabelModuler110.setText("Moduler IS-110");

        jButtonModul6.setText("Modul 6");
        jButtonModul6.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul6ActionPerformed(evt);
            }
        });

        jButtonModul7.setText("Modul 7");
        jButtonModul7.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul7ActionPerformed(evt);
            }
        });

        jButtonModul8.setText("Modul 8");
        jButtonModul8.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul8ActionPerformed(evt);
            }
        });

        jButtonModul9.setText("Modul 9");
        jButtonModul9.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul9ActionPerformed(evt);
            }
        });

        jButtonModul10.setText("Modul 10");
        jButtonModul10.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul10ActionPerformed(evt);
            }
        });

        jButtonModul11.setText("Modul 11");
        jButtonModul11.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul11ActionPerformed(evt);
            }
        });

        jButtonModul12.setText("Modul 12");
        jButtonModul12.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul12ActionPerformed(evt);
            }
        });

        jButtonModul13.setText("Modul 13");
        jButtonModul13.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul13ActionPerformed(evt);
            }
        });

        jButtonModul14.setText("Modul 14");
        jButtonModul14.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul14ActionPerformed(evt);
            }
        });

        jLabel2.setText("Skriv litt generell info om kurset");

        jButtonLagreInfo.setText("Lagre");
        jButtonLagreInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLagreInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModulerLayout = new javax.swing.GroupLayout(jPanelModuler);
        jPanelModuler.setLayout(jPanelModulerLayout);
        jPanelModulerLayout.setHorizontalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonModul4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jLabelModuler109, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModul5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModulerLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonModul6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(jButtonModul14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonModul7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonModul8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonModul9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonModul10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonModul11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonModul12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelModuler110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModulerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonModul13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(99, Short.MAX_VALUE))
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLagreInfo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelModulerLayout.setVerticalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModuler109)
                            .addComponent(jLabelModuler110))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModul5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModul10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModul14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonLagreInfo)
                        .addGroup(jPanelModulerLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Moduler", jPanelModuler);

        jScrollPane12.setViewportView(jList1);

        jButton1.setText("Vis profil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInnleveringLayout = new javax.swing.GroupLayout(jPanelInnlevering);
        jPanelInnlevering.setLayout(jPanelInnleveringLayout);
        jPanelInnleveringLayout.setHorizontalGroup(
            jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInnleveringLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(483, Short.MAX_VALUE))
        );
        jPanelInnleveringLayout.setVerticalGroup(
            jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInnleveringLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Innlevering", jPanelInnlevering);

        jPanelStatistikk.setLayout(new java.awt.BorderLayout());

        jPanelStatistikkMain.setLayout(new javax.swing.BoxLayout(jPanelStatistikkMain, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaId.setEditable(false);
        jTextAreaId.setColumns(20);
        jTextAreaId.setRows(5);
        jScrollPane2.setViewportView(jTextAreaId);

        jPanelStatistikkMain.add(jScrollPane2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaName.setEditable(false);
        jTextAreaName.setColumns(20);
        jTextAreaName.setRows(5);
        jScrollPane3.setViewportView(jTextAreaName);

        jPanelStatistikkMain.add(jScrollPane3);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaSurname.setEditable(false);
        jTextAreaSurname.setColumns(20);
        jTextAreaSurname.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSurname);

        jPanelStatistikkMain.add(jScrollPane4);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaDate.setEditable(false);
        jTextAreaDate.setColumns(20);
        jTextAreaDate.setRows(5);
        jScrollPane5.setViewportView(jTextAreaDate);

        jPanelStatistikkMain.add(jScrollPane5);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaLeverte.setEditable(false);
        jTextAreaLeverte.setColumns(20);
        jTextAreaLeverte.setRows(5);
        jScrollPane6.setViewportView(jTextAreaLeverte);

        jPanelStatistikkMain.add(jScrollPane6);

        jPanelStatistikk.add(jPanelStatistikkMain, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Statistikk", jPanelStatistikk);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Statusrapport:");

        jLabelStatusrapportQuestion1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion1.setText("Hvilken modul har du jobbet med?");

        jLabelStatusrapportQuestion3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion3.setText("Har du møtt på noen problemer?");

        jLabelStatusrapportQuestion5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion5.setText("Har du et tema du ønsker at vi skal gjennom gå i en forelsning? ");

        jLabelStatusrapportQuestion4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion4.setText("Hva har du lært?");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane7.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane8.setViewportView(jTextArea4);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane9.setViewportView(jTextArea5);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane10.setViewportView(jTextArea6);

        jButtonSendRapport.setText("Send/lagre");

        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane11.setViewportView(jTextArea7);

        jLabelStatusrapportQuestion2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatusrapportQuestion2.setText("Hva gar du jobbet med denne uken?");

        javax.swing.GroupLayout jPanelStatusrapportLayout = new javax.swing.GroupLayout(jPanelStatusrapport);
        jPanelStatusrapport.setLayout(jPanelStatusrapportLayout);
        jPanelStatusrapportLayout.setHorizontalGroup(
            jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusrapportLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSendRapport)
                    .addGroup(jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelStatusrapportQuestion1)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStatusrapportQuestion5)
                        .addComponent(jLabelStatusrapportQuestion2)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStatusrapportQuestion3)
                        .addComponent(jLabelStatusrapportQuestion4)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanelStatusrapportLayout.setVerticalGroup(
            jPanelStatusrapportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusrapportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStatusrapportQuestion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStatusrapportQuestion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStatusrapportQuestion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStatusrapportQuestion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStatusrapportQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSendRapport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Statusrapport", jPanelStatusrapport);

        jPanelMøteLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelMøteLeft.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 25, 0, 0);
        jPanelMøteLeft.add(jTextFieldDeltaker, gridBagConstraints);

        jLabelMøtedeltaker.setText("Møtedeltaker:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 28, 0, 0);
        jPanelMøteLeft.add(jLabelMøtedeltaker, gridBagConstraints);

        jLabelTidspunkt.setText("Tidspunkt:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 28, 0, 0);
        jPanelMøteLeft.add(jLabelTidspunkt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 25, 0, 0);
        jPanelMøteLeft.add(jTextFieldTidspunkt, gridBagConstraints);

        jLabelSted.setText("Sted:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 28, 0, 0);
        jPanelMøteLeft.add(jLabelSted, gridBagConstraints);

        jTextFieldSted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStedActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 25, 0, 0);
        jPanelMøteLeft.add(jTextFieldSted, gridBagConstraints);

        jButtonLagre.setText("Lagre");
        jButtonLagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLagreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 15, 243, 0);
        jPanelMøteLeft.add(jButtonLagre, gridBagConstraints);

        jButtonSlett.setText("Slett");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 26, 243, 145);
        jPanelMøteLeft.add(jButtonSlett, gridBagConstraints);

        jPanelMøte.add(jPanelMøteLeft);

        jPanelMøteTop.setLayout(new javax.swing.BoxLayout(jPanelMøteTop, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMøte.add(jPanelMøteTop);

        jPanelMøtebot.setLayout(new javax.swing.BoxLayout(jPanelMøtebot, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMøte.add(jPanelMøtebot);

        jPanelMøteRight.setLayout(new javax.swing.BoxLayout(jPanelMøteRight, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMøte.add(jPanelMøteRight);

        jPanelMøteCentre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Møteplan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanelMøteCentre.setLayout(new javax.swing.BoxLayout(jPanelMøteCentre, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelMøteCentre.add(jScrollPane1);

        jPanelMøte.add(jPanelMøteCentre);

        jTabbedPane1.addTab("Møte", jPanelMøte);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void statistikkVisning() {
        try {

            String db_url = "jdbc:mysql://localhost:3306/slit";
            String db_user = "root";
            String db_pass = "root";
            
            System.out.println("The URL is: " + db_url);
            Connection con = DriverManager.getConnection(db_url, db_user, db_pass);
            
            Statement stmt = con.createStatement( );
            String SQL ="SELECT * FROM Statistikk";
            ResultSet result = stmt.executeQuery (SQL);
            
            int id_col = 0;
            String name = "";
            String surname ="";
            String dato = "";
            int antLeverte = 0;

            while (result.next() ) {
                id_col = result.getInt("Bruker_brukerId");
                name = result.getString("brukerFornavn");
                surname = result.getString("brukerEtternavn");
                dato = result.getString("modulfilDato");
                antLeverte = result.getInt("COUNT(sensurId)");
              //  System.out.println("ID: "+ " " + id_col +"     " +  "Fornavn: " + 
              //      "     " + name + "     " + "Etternavn: " +" "+ surname + "     " 
              //          + "Dato og klokkeslett:" + " " + dato + "     "
              //      + "Antall godkjente moduler:" + antLeverte);
                
                jTextAreaId.append(" " + "Bruker ID:"+ " " + id_col + newline);
                jTextAreaName.append(" " + "Fornavn:" + " " + name + newline);
                jTextAreaSurname.append(" " + "Etternavn:" + " " + surname + newline);
                jTextAreaDate.append(" " + "Aktivitet:" + " " + dato + newline);
                jTextAreaLeverte.append(" " + "Moduler med sensur:" + " " + antLeverte + newline);
                /**
                " +  "Fornavn: " + 
                    " " + name + "          " + "Etternavn: " +" "+ surname + "          " 
                        + "Dato og klokkeslett:" + " " + dato + "          "
                    + "Antall godkjente moduler:" + antLeverte + " "
                        + newline);
                        * /
                        
                // For å gjøre int om til string, om det trengs
                /**
                StringBuilder ID = new StringBuilder();
                    ID.append("");
                    ID.append(id_col);
                    String idString = ID.toString();
                
                StringBuilder leverte = new StringBuilder();
                    leverte.append("");
                    leverte.append(antLeverte);
                    String antLeverteString = leverte.toString();
               */     
            }
            
            
            
            
           
        }
          catch (SQLException err) {
            System.out.println( err.getMessage( ));
            
        } 
       
        
    }
    public localUser profilVisning () {
        String user = Main.user.getUser();
        String rolle = Main.user.getRole();
        jTextAreaProfil.append("Brukernavn:" + "   " +user);
        jTextAreaProfil.append(newline);
        jTextAreaProfil.append("Rolle:" + "   " + rolle);
        return Main.user;
    }
    public void hentProfil() {
        try {
                String profilNavn = jList1.getSelectedValue().toString();
                String SQL = ("SELECT * FROM Bruker where brukerEtternavn = '"+profilNavn+"'");
                
                Connection con = DriverManager.getConnection(Constants.db_url, Constants.db_user, Constants.db_pass);
             
                Statement stmt = con.createStatement( );
                ResultSet rs = stmt.executeQuery (SQL);
                
                int brukerId = 0;
                if (rs.next()) {
                    brukerId = rs.getInt("brukerId");
                    setBrukerNavn(rs.getString("brukerFornavn")); 
                    System.out.println("Vis profilen til" + " " + profilNavn);
                    StudentProfil profil = new StudentProfil();
                    profil.setVisible(true);
                }
                String SQL2 = ("SELECT * FROM Bruker WHERE brukerId = '"+brukerId+"'");
                
                
           
        }
        catch (SQLException err) {
            System.out.println(err);
        }
    }
    public void hentBrukere () {
         try {
            DefaultListModel DML = new DefaultListModel();
             Connection con = DriverManager.getConnection(Constants.db_url, Constants.db_user, Constants.db_pass);
       
               
                String SQL = ("SELECT * from Bruker WHERE brukerRolle = 'student'");      
                String brukerFornavn = "";
                String brukerEtternavn = "";
                Statement hentBrukere = con.createStatement( );
                ResultSet rs = hentBrukere.executeQuery (SQL);
                
                    while (rs.next()) {
                      brukerFornavn = rs.getString("brukerFornavn");
                      brukerEtternavn = rs.getString("brukerEtternavn");
                      DML.addElement (brukerEtternavn);
                    //  arrayList.add(brukerFornavn + brukerEtternavn);
                }
                jList1.setModel(DML);
        
        }
        catch (SQLException err) {
            System.out.println(err);
        }
    }
    private void jButtonModul5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul5ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 5");
       moduleInformationWindowForeleser modul5 = new moduleInformationWindowForeleser();
       modul5.hentPublisert();
       modul5.setVisible(true);
    }//GEN-LAST:event_jButtonModul5ActionPerformed

    private void jButtonModul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul3ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 3");
       moduleInformationWindowForeleser modul3 = new moduleInformationWindowForeleser();
       modul3.hentPublisert();
       modul3.setVisible(true);
    }//GEN-LAST:event_jButtonModul3ActionPerformed

    private void jButtonModul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul1ActionPerformed
        
    // TODO add your handling code here:
       setModulTrykket("modul 1");
       moduleInformationWindowForeleser modul1 = new moduleInformationWindowForeleser();
       modul1.hentPublisert();
       modul1.setVisible(true);
    }//GEN-LAST:event_jButtonModul1ActionPerformed

    private void jTextFieldStedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStedActionPerformed

    private void jButtonLagreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLagreActionPerformed
        // TODO add your handling code here:
        // Setter variablene til queries
        tidspunkt = jTextFieldTidspunkt.getText();
        idString = jTextFieldDeltaker.getText();
        // Må gjøre om verdien i tekstfeltene til int før de skal inn i DB
        // Try-catch for å håndtere feil format i feltene
        

        try {
            id = Integer.parseInt(idString);
        }
        catch (NumberFormatException feilId) {
            System.out.println(feilId);
        }
        // Resten av verdiene er tekst også i databasen
        møtested = jTextFieldSted.getText();

        sendMøteInformasjon();
        
	jTextFieldSted.setText("");
        jTextFieldTidspunkt.setText("");
        jTextFieldDeltaker.setText("");
        
        JOptionPane.showMessageDialog(null, "<Møtet er blitt lagret>", "Alert", JOptionPane.INFORMATION_MESSAGE);
            // TODO add your handling code here:
        
        
        
        
    }                                            
        private void sendMøteInformasjon() {
        if (Main.user != null)
        db.sendMøteInfo(id, tidspunkt, møtested);
        
        
        
    }//GEN-LAST:event_jButtonLagreActionPerformed

    private void jButtonModul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul2ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 2");
       moduleInformationWindowForeleser modul2 = new moduleInformationWindowForeleser();
       modul2.hentPublisert();
       modul2.setVisible(true);
    }//GEN-LAST:event_jButtonModul2ActionPerformed

    private void jButtonModul4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul4ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 4");
       moduleInformationWindowForeleser modul4 = new moduleInformationWindowForeleser();
       modul4.hentPublisert();
       modul4.setVisible(true);
    }//GEN-LAST:event_jButtonModul4ActionPerformed

    private void jButtonModul6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul6ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 6");
       moduleInformationWindowForeleser modul6 = new moduleInformationWindowForeleser();
       modul6.hentPublisert();
       modul6.setVisible(true);
    }//GEN-LAST:event_jButtonModul6ActionPerformed

    private void jButtonModul7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul7ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 7");
       moduleInformationWindowForeleser modul7 = new moduleInformationWindowForeleser();
       modul7.hentPublisert();
       modul7.setVisible(true);
    }//GEN-LAST:event_jButtonModul7ActionPerformed

    private void jButtonModul8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul8ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 8");
       moduleInformationWindowForeleser modul8 = new moduleInformationWindowForeleser();
       modul8.hentPublisert();
       modul8.setVisible(true);
    }//GEN-LAST:event_jButtonModul8ActionPerformed

    private void jButtonModul9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul9ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 9");
       moduleInformationWindowForeleser modul9 = new moduleInformationWindowForeleser();
       modul9.hentPublisert();
       modul9.setVisible(true);
    }//GEN-LAST:event_jButtonModul9ActionPerformed

    private void jButtonModul10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul10ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 10");
       moduleInformationWindowForeleser modul10 = new moduleInformationWindowForeleser();
       modul10.hentPublisert();
       modul10.setVisible(true);
    }//GEN-LAST:event_jButtonModul10ActionPerformed

    private void jButtonModul11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul11ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 11");
       moduleInformationWindowForeleser modul11 = new moduleInformationWindowForeleser();
       modul11.hentPublisert();
       modul11.setVisible(true);
       
    }//GEN-LAST:event_jButtonModul11ActionPerformed

    private void jButtonModul12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul12ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 12");
       moduleInformationWindowForeleser modul12 = new moduleInformationWindowForeleser();
       modul12.hentPublisert();
       modul12.setVisible(true);
    }//GEN-LAST:event_jButtonModul12ActionPerformed

    private void jButtonModul13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul13ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 13");
       moduleInformationWindowForeleser modul13 = new moduleInformationWindowForeleser();
       modul13.hentPublisert();
       modul13.setVisible(true);
    }//GEN-LAST:event_jButtonModul13ActionPerformed

    private void jButtonModul14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul14ActionPerformed
        // TODO add your handling code here:
       setModulTrykket("modul 14");
       moduleInformationWindowForeleser modul14 = new moduleInformationWindowForeleser();
       modul14.hentPublisert();
       modul14.setVisible(true);
    }//GEN-LAST:event_jButtonModul14ActionPerformed

    private void jButtonLagreInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLagreInfoActionPerformed
        // TODO add your handling code here:
        setGenerellModul(jTextAreaInfo.getText());
        System.out.println(getGenerellModul());
        slit.db.generellInfo();
        slit.db.hentGammelBeskjed();
    }//GEN-LAST:event_jButtonLagreInfoActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        db.hentGammelBeskjed();
        jTextAreaInfo.setText(getGenerellModul());
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void profilUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilUploadActionPerformed
        //        // TODO add your handling code here:
        //         int returnVal = fileChooser.showOpenDialog(this);
        //    if (returnVal == JFileChooser.APPROVE_OPTION) {
            //        File file = fileChooser.getSelectedFile();
            //        try {
                //          // What to do with the file, e.g. display it in a TextArea
                //          textarea.read(new FileReader( file.getAbsolutePath() ), null );
                //        } catch (IOException ex) {
                //          System.out.println("problem accessing file"+file.getAbsolutePath());
                //        }
            //    } else {
            //        System.out.println("File access cancelled by user.");
            //    }

    }//GEN-LAST:event_profilUploadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       setValgtBruker(jList1.getSelectedValue().toString());
       hentProfil();
       
      
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindowForeleser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindowForeleser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindowForeleser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindowForeleser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindowForeleser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLagre;
    private javax.swing.JButton jButtonLagreInfo;
    private javax.swing.JButton jButtonModul1;
    private javax.swing.JButton jButtonModul10;
    private javax.swing.JButton jButtonModul11;
    private javax.swing.JButton jButtonModul12;
    private javax.swing.JButton jButtonModul13;
    private javax.swing.JButton jButtonModul14;
    private javax.swing.JButton jButtonModul2;
    private javax.swing.JButton jButtonModul3;
    private javax.swing.JButton jButtonModul4;
    private javax.swing.JButton jButtonModul5;
    private javax.swing.JButton jButtonModul6;
    private javax.swing.JButton jButtonModul7;
    private javax.swing.JButton jButtonModul8;
    private javax.swing.JButton jButtonModul9;
    private javax.swing.JButton jButtonSendRapport;
    private javax.swing.JButton jButtonSlett;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelModuler109;
    private javax.swing.JLabel jLabelModuler110;
    private javax.swing.JLabel jLabelMøtedeltaker;
    private javax.swing.JLabel jLabelStatusrapportQuestion1;
    private javax.swing.JLabel jLabelStatusrapportQuestion2;
    private javax.swing.JLabel jLabelStatusrapportQuestion3;
    private javax.swing.JLabel jLabelStatusrapportQuestion4;
    private javax.swing.JLabel jLabelStatusrapportQuestion5;
    private javax.swing.JLabel jLabelSted;
    private javax.swing.JLabel jLabelTidspunkt;
    private javax.swing.JLabel jLabelTittel;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanelBotMain;
    private javax.swing.JPanel jPanelHjem;
    private javax.swing.JPanel jPanelInnlevering;
    private javax.swing.JPanel jPanelLeftCentre;
    private javax.swing.JPanel jPanelLeftLeft;
    private javax.swing.JPanel jPanelLeftMain;
    private javax.swing.JPanel jPanelLeftRight;
    private javax.swing.JPanel jPanelLeftRightRight;
    private javax.swing.JPanel jPanelModuler;
    private javax.swing.JPanel jPanelMøte;
    private javax.swing.JPanel jPanelMøteCentre;
    private javax.swing.JPanel jPanelMøteLeft;
    private javax.swing.JPanel jPanelMøteRight;
    private javax.swing.JPanel jPanelMøteTop;
    private javax.swing.JPanel jPanelMøtebot;
    private javax.swing.JPanel jPanelRightMain;
    private javax.swing.JPanel jPanelStatistikk;
    private javax.swing.JPanel jPanelStatistikkMain;
    private javax.swing.JPanel jPanelStatusrapport;
    private javax.swing.JPanel jPanelTopBot;
    private javax.swing.JPanel jPanelTopCentre;
    private javax.swing.JPanel jPanelTopMain;
    private javax.swing.JPanel jPanelTopTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPaneMeny;
    private javax.swing.JScrollPane jScrollPaneModuloversikt;
    private javax.swing.JSeparator jSeperatorLeftLeft;
    private javax.swing.JSeparator jSeperatorLeftRight;
    private javax.swing.JSeparator jSeperatorTopBot;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextAreaDate;
    private javax.swing.JTextArea jTextAreaId;
    private javax.swing.JTextArea jTextAreaInfo;
    private javax.swing.JTextArea jTextAreaLeverte;
    private javax.swing.JTextArea jTextAreaName;
    private javax.swing.JTextArea jTextAreaProfil;
    private javax.swing.JTextArea jTextAreaSurname;
    private javax.swing.JTextField jTextFieldDeltaker;
    private javax.swing.JTextField jTextFieldSted;
    private javax.swing.JTextField jTextFieldTidspunkt;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTree jTreeMeny;
    private javax.swing.JLabel profilTitle;
    private javax.swing.JButton profilUpload;
    // End of variables declaration//GEN-END:variables
}
