/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slit.client.foreleser;

import slit.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import slit.Sensur.Sensur;
import slit.lastNed.lastNed;
/**
 *
 * @author Sondre, Michael, Erik, Christian Fredrik, Thomas, Gruppe 109
 * GUI klasse for foreleser, mainWindowForelser. Også her en del logikk grunnet mangel på tid
 * til å gjøre endringer i hele systemet.
 */
public class mainWindowForeleser extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     * 
     */
   
   // ArrayList<String> arrayList = new ArrayList<String>(); 
   private static String modulTrykket = "";
   private static String generellModul = "";
   private static String valgtBruker = "";
   private static String brukerNavn = "";

    public static String getBrukerNavn() {
        return brukerNavn;
    }

    public static void setBrukerNavn(String brukerNavn) {
        mainWindowForeleser.brukerNavn = brukerNavn;
    }

    public static String getValgtBruker() {
        return valgtBruker;
    }

    public static void setValgtBruker(String valgtBruker) {
        mainWindowForeleser.valgtBruker = valgtBruker;
    }
    public static String getGenerellModul () {
        return generellModul;
    }
    public void setGenerellModul(String generellModul) {
        this.generellModul = generellModul;       
    }
    public static String getModulTrykket() {
        return modulTrykket;
    }

    public  void setModulTrykket(String modulTrykket) {
        this.modulTrykket = modulTrykket;
    }
    final static String newline = "\n";
    public mainWindowForeleser() {  
        initComponents();
        statistikkVisning();
        profilVisning ();
        hentBrukere();
        hentMøte();
        hentDagens();
        
        
        
    }
    
    private String user = "";
    private String pass ="";
    private String tidspunkt = "";
    private String møtested ="";
    private String tidspunktString = "";
    private int id = 0;
    private String idString = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanelTopMain = new javax.swing.JPanel();
        jPanelTopCentre = new javax.swing.JPanel();
        jLabelTittel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelTopTop = new javax.swing.JPanel();
        jPanelTopBot = new javax.swing.JPanel();
        jSeperatorTopBot = new javax.swing.JSeparator();
        jPanelLeftMain = new javax.swing.JPanel();
        jPanelLeftLeft = new javax.swing.JPanel();
        jSeperatorLeftLeft = new javax.swing.JSeparator();
        jPanelLeftCentre = new javax.swing.JPanel();
        jScrollPaneMeny = new javax.swing.JScrollPane();
        jTreeMeny = new javax.swing.JTree();
        jPanelLeftRight = new javax.swing.JPanel();
        jSeperatorLeftRight = new javax.swing.JSeparator();
        jPanelLeftRightRight = new javax.swing.JPanel();
        jPanelBotMain = new javax.swing.JPanel();
        jPanelRightMain = new javax.swing.JPanel();
        profilTitle = new javax.swing.JLabel();
        jLabelBruker = new javax.swing.JLabel();
        jLabelRolle = new javax.swing.JLabel();
        jTabbedPaneBrukerliste = new javax.swing.JTabbedPane();
        jPanelHjem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDagens = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jPanelModuler = new javax.swing.JPanel();
        jScrollPaneModuloversikt = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jLabelModuler109 = new javax.swing.JLabel();
        jButtonModul1 = new javax.swing.JButton();
        jButtonModul2 = new javax.swing.JButton();
        jButtonModul3 = new javax.swing.JButton();
        jButtonModul4 = new javax.swing.JButton();
        jButtonModul5 = new javax.swing.JButton();
        jLabelModuler110 = new javax.swing.JLabel();
        jButtonModul6 = new javax.swing.JButton();
        jButtonModul7 = new javax.swing.JButton();
        jButtonModul8 = new javax.swing.JButton();
        jButtonModul9 = new javax.swing.JButton();
        jButtonModul10 = new javax.swing.JButton();
        jButtonModul11 = new javax.swing.JButton();
        jButtonModul12 = new javax.swing.JButton();
        jButtonModul13 = new javax.swing.JButton();
        jButtonModul14 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonLagreInfo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelInnlevering = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jPanelStatistikk = new javax.swing.JPanel();
        jPanelStatistikkMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaId = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaName = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSurname = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDate = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaLeverte = new javax.swing.JTextArea();
        jPanelMøte = new javax.swing.JPanel();
        jPanelMøteLeft = new javax.swing.JPanel();
        jLabelTidspunkt = new javax.swing.JLabel();
        jTextFieldTidspunkt = new javax.swing.JTextField();
        jLabelSted = new javax.swing.JLabel();
        jTextFieldSted = new javax.swing.JTextField();
        jButtonLagre = new javax.swing.JButton();
        jButtonSlett = new javax.swing.JButton();
        jPanelMøteTop = new javax.swing.JPanel();
        jPanelMøtebot = new javax.swing.JPanel();
        jPanelMøteRight = new javax.swing.JPanel();
        jPanelMøteCentre = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jListMøte = new javax.swing.JList();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTopMain.setLayout(new java.awt.BorderLayout());

        jLabelTittel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabelTittel.setText("Programmeringsprosjekt IS-202, Gruppe 109");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slit/UiA logo_middels_None.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelTopCentreLayout = new javax.swing.GroupLayout(jPanelTopCentre);
        jPanelTopCentre.setLayout(jPanelTopCentreLayout);
        jPanelTopCentreLayout.setHorizontalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabelTittel)
                .addContainerGap(939, Short.MAX_VALUE))
        );
        jPanelTopCentreLayout.setVerticalGroup(
            jPanelTopCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopCentreLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopCentreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTittel)
                .addGap(38, 38, 38))
        );

        jPanelTopMain.add(jPanelTopCentre, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelTopTopLayout = new javax.swing.GroupLayout(jPanelTopTop);
        jPanelTopTop.setLayout(jPanelTopTopLayout);
        jPanelTopTopLayout.setHorizontalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1837, Short.MAX_VALUE)
        );
        jPanelTopTopLayout.setVerticalGroup(
            jPanelTopTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanelTopMain.add(jPanelTopTop, java.awt.BorderLayout.PAGE_START);

        jSeperatorTopBot.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorTopBot.setPreferredSize(new java.awt.Dimension(50, 1));

        javax.swing.GroupLayout jPanelTopBotLayout = new javax.swing.GroupLayout(jPanelTopBot);
        jPanelTopBot.setLayout(jPanelTopBotLayout);
        jPanelTopBotLayout.setHorizontalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1837, Short.MAX_VALUE)
        );
        jPanelTopBotLayout.setVerticalGroup(
            jPanelTopBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBotLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeperatorTopBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanelTopMain.add(jPanelTopBot, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanelTopMain, java.awt.BorderLayout.PAGE_START);

        jPanelLeftLeft.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftLeft.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftLeft.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftLeft.add(jSeperatorLeftLeft, java.awt.BorderLayout.CENTER);

        jPanelLeftCentre.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Hurtignavigering");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Moduler");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Moduloversikt");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduler IS-109");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 1");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 2");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 3");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 4");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Moduer IS-110");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 5");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 6");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 7");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 8");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 9");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 10");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 11");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 12");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 13");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Modul 14");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Innlevering 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("osv");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Møte");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Statusrapport");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Hjelp");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("FAQ");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Forum");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("IM");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Om systemet");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeMeny.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeMeny.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPaneMeny.setViewportView(jTreeMeny);

        jPanelLeftCentre.add(jScrollPaneMeny, java.awt.BorderLayout.CENTER);

        jPanelLeftRight.setLayout(new java.awt.BorderLayout());

        jSeperatorLeftRight.setForeground(new java.awt.Color(0, 0, 0));
        jSeperatorLeftRight.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelLeftRight.add(jSeperatorLeftRight, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelLeftRightRightLayout = new javax.swing.GroupLayout(jPanelLeftRightRight);
        jPanelLeftRightRight.setLayout(jPanelLeftRightRightLayout);
        jPanelLeftRightRightLayout.setHorizontalGroup(
            jPanelLeftRightRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanelLeftRightRightLayout.setVerticalGroup(
            jPanelLeftRightRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLeftMainLayout = new javax.swing.GroupLayout(jPanelLeftMain);
        jPanelLeftMain.setLayout(jPanelLeftMainLayout);
        jPanelLeftMainLayout.setHorizontalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanelLeftRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanelLeftRightRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLeftMainLayout.setVerticalGroup(
            jPanelLeftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeftLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLeftCentre, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
            .addComponent(jPanelLeftRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLeftRightRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLeftMain, java.awt.BorderLayout.LINE_START);
        getContentPane().add(jPanelBotMain, java.awt.BorderLayout.PAGE_END);

        profilTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        profilTitle.setForeground(new java.awt.Color(0, 0, 204));
        profilTitle.setText("Profil");

        jLabelBruker.setText("jLabel4");

        jLabelRolle.setText("jLabel5");

        javax.swing.GroupLayout jPanelRightMainLayout = new javax.swing.GroupLayout(jPanelRightMain);
        jPanelRightMain.setLayout(jPanelRightMainLayout);
        jPanelRightMainLayout.setHorizontalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRightMainLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(profilTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanelRightMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBruker)
                    .addComponent(jLabelRolle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRightMainLayout.setVerticalGroup(
            jPanelRightMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightMainLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(profilTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBruker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRolle)
                .addContainerGap(543, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelRightMain, java.awt.BorderLayout.LINE_END);

        jTabbedPaneBrukerliste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneBrukerlisteMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Skriv inn dagens melding");

        jTextAreaDagens.setColumns(20);
        jTextAreaDagens.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDagens);

        jButton4.setText("Lagre");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHjemLayout = new javax.swing.GroupLayout(jPanelHjem);
        jPanelHjem.setLayout(jPanelHjemLayout);
        jPanelHjemLayout.setHorizontalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHjemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(752, Short.MAX_VALUE))
        );
        jPanelHjemLayout.setVerticalGroup(
            jPanelHjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHjemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        jTabbedPaneBrukerliste.addTab("Hjem", jPanelHjem);

        jTextAreaInfo.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaInfo.setColumns(20);
        jTextAreaInfo.setRows(5);
        jTextAreaInfo.setText("\n");
        jTextAreaInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneModuloversikt.setViewportView(jTextAreaInfo);

        jLabelModuler109.setText("Moduler IS-109");

        jButtonModul1.setText("Modul 1");
        jButtonModul1.setMaximumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setMinimumSize(new java.awt.Dimension(79, 23));
        jButtonModul1.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul1ActionPerformed(evt);
            }
        });

        jButtonModul2.setText("Modul 2");
        jButtonModul2.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul2ActionPerformed(evt);
            }
        });

        jButtonModul3.setText("Modul 3");
        jButtonModul3.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul3ActionPerformed(evt);
            }
        });

        jButtonModul4.setText("Modul 4");
        jButtonModul4.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul4ActionPerformed(evt);
            }
        });

        jButtonModul5.setText("Modul 5");
        jButtonModul5.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul5ActionPerformed(evt);
            }
        });

        jLabelModuler110.setText("Moduler IS-110");

        jButtonModul6.setText("Modul 6");
        jButtonModul6.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul6ActionPerformed(evt);
            }
        });

        jButtonModul7.setText("Modul 7");
        jButtonModul7.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul7ActionPerformed(evt);
            }
        });

        jButtonModul8.setText("Modul 8");
        jButtonModul8.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul8ActionPerformed(evt);
            }
        });

        jButtonModul9.setText("Modul 9");
        jButtonModul9.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul9ActionPerformed(evt);
            }
        });

        jButtonModul10.setText("Modul 10");
        jButtonModul10.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul10ActionPerformed(evt);
            }
        });

        jButtonModul11.setText("Modul 11");
        jButtonModul11.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul11ActionPerformed(evt);
            }
        });

        jButtonModul12.setText("Modul 12");
        jButtonModul12.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul12ActionPerformed(evt);
            }
        });

        jButtonModul13.setText("Modul 13");
        jButtonModul13.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul13ActionPerformed(evt);
            }
        });

        jButtonModul14.setText("Modul 14");
        jButtonModul14.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonModul14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModul14ActionPerformed(evt);
            }
        });

        jLabel2.setText("Skriv litt generell info om kurset");

        jButtonLagreInfo.setText("Lagre");
        jButtonLagreInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLagreInfoActionPerformed(evt);
            }
        });

        jButton2.setText("Last ned modulfiler fra elevene");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Gi sensur på elevenes innleveringer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModulerLayout = new javax.swing.GroupLayout(jPanelModuler);
        jPanelModuler.setLayout(jPanelModulerLayout);
        jPanelModulerLayout.setHorizontalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModulerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLagreInfo))
                            .addGroup(jPanelModulerLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButtonModul4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelModuler109, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonModul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonModul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonModul3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonModul5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButtonModul6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonModul14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonModul7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonModul8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonModul9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonModul10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonModul11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonModul12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelModuler110, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButtonModul13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(592, Short.MAX_VALUE))
        );
        jPanelModulerLayout.setVerticalGroup(
            jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModulerLayout.createSequentialGroup()
                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLagreInfo)
                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModulerLayout.createSequentialGroup()
                                .addGroup(jPanelModulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                                        .addComponent(jLabelModuler109)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonModul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jButtonModul3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelModulerLayout.createSequentialGroup()
                                        .addComponent(jLabelModuler110)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonModul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jButtonModul8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonModul14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addComponent(jButton2)
                                .addGap(21, 21, 21)
                                .addComponent(jButton3))
                            .addComponent(jScrollPaneModuloversikt, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jTabbedPaneBrukerliste.addTab("Moduler", jPanelModuler);

        jScrollPane12.setViewportView(jList1);

        jButton1.setText("Vis profil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInnleveringLayout = new javax.swing.GroupLayout(jPanelInnlevering);
        jPanelInnlevering.setLayout(jPanelInnleveringLayout);
        jPanelInnleveringLayout.setHorizontalGroup(
            jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInnleveringLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(917, Short.MAX_VALUE))
        );
        jPanelInnleveringLayout.setVerticalGroup(
            jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInnleveringLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelInnleveringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jTabbedPaneBrukerliste.addTab("Brukerliste", jPanelInnlevering);

        jPanelStatistikk.setLayout(new java.awt.BorderLayout());

        jPanelStatistikkMain.setLayout(new javax.swing.BoxLayout(jPanelStatistikkMain, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaId.setEditable(false);
        jTextAreaId.setColumns(20);
        jTextAreaId.setRows(5);
        jScrollPane2.setViewportView(jTextAreaId);

        jPanelStatistikkMain.add(jScrollPane2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaName.setEditable(false);
        jTextAreaName.setColumns(20);
        jTextAreaName.setRows(5);
        jScrollPane3.setViewportView(jTextAreaName);

        jPanelStatistikkMain.add(jScrollPane3);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaSurname.setEditable(false);
        jTextAreaSurname.setColumns(20);
        jTextAreaSurname.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSurname);

        jPanelStatistikkMain.add(jScrollPane4);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaDate.setEditable(false);
        jTextAreaDate.setColumns(20);
        jTextAreaDate.setRows(5);
        jScrollPane5.setViewportView(jTextAreaDate);

        jPanelStatistikkMain.add(jScrollPane5);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaLeverte.setEditable(false);
        jTextAreaLeverte.setColumns(20);
        jTextAreaLeverte.setRows(5);
        jScrollPane6.setViewportView(jTextAreaLeverte);

        jPanelStatistikkMain.add(jScrollPane6);

        jPanelStatistikk.add(jPanelStatistikkMain, java.awt.BorderLayout.CENTER);

        jTabbedPaneBrukerliste.addTab("Statistikk", jPanelStatistikk);

        jPanelMøteLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTidspunkt.setText("Tidspunkt:");

        jLabelSted.setText("Sted:");

        jTextFieldSted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStedActionPerformed(evt);
            }
        });

        jButtonLagre.setText("Lagre");
        jButtonLagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLagreActionPerformed(evt);
            }
        });

        jButtonSlett.setText("Slett");

        javax.swing.GroupLayout jPanelMøteLeftLayout = new javax.swing.GroupLayout(jPanelMøteLeft);
        jPanelMøteLeft.setLayout(jPanelMøteLeftLayout);
        jPanelMøteLeftLayout.setHorizontalGroup(
            jPanelMøteLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMøteLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMøteLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMøteLeftLayout.createSequentialGroup()
                        .addComponent(jLabelSted, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSted, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMøteLeftLayout.createSequentialGroup()
                        .addComponent(jLabelTidspunkt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jTextFieldTidspunkt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanelMøteLeftLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButtonLagre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSlett)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMøteLeftLayout.setVerticalGroup(
            jPanelMøteLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMøteLeftLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelMøteLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTidspunkt)
                    .addComponent(jTextFieldTidspunkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMøteLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSted)
                    .addComponent(jTextFieldSted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanelMøteLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLagre)
                    .addComponent(jButtonSlett))
                .addGap(71, 71, 71))
        );

        jPanelMøteTop.setLayout(new javax.swing.BoxLayout(jPanelMøteTop, javax.swing.BoxLayout.LINE_AXIS));

        jPanelMøtebot.setLayout(new javax.swing.BoxLayout(jPanelMøtebot, javax.swing.BoxLayout.LINE_AXIS));

        jPanelMøteRight.setLayout(new javax.swing.BoxLayout(jPanelMøteRight, javax.swing.BoxLayout.LINE_AXIS));

        jPanelMøteCentre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Møteplan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanelMøteCentre.setLayout(new java.awt.GridBagLayout());

        jListMøte.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane14.setViewportView(jListMøte);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 376;
        gridBagConstraints.ipady = 287;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(48, 12, 74, 6);
        jPanelMøteCentre.add(jScrollPane14, gridBagConstraints);

        javax.swing.GroupLayout jPanelMøteLayout = new javax.swing.GroupLayout(jPanelMøte);
        jPanelMøte.setLayout(jPanelMøteLayout);
        jPanelMøteLayout.setHorizontalGroup(
            jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMøteLayout.createSequentialGroup()
                .addGroup(jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMøteRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMøteTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMøtebot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMøteLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanelMøteLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelMøteCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jPanelMøteLayout.setVerticalGroup(
            jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMøteLayout.createSequentialGroup()
                .addGroup(jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMøteRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMøteTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMøtebot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelMøteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMøteLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jPanelMøteLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMøteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanelMøteCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPaneBrukerliste.addTab("Møte", jPanelMøte);

        getContentPane().add(jTabbedPaneBrukerliste, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Foreleser sender dagens melding på hjem-tab.
     * dagens melding skal kun ha 1 oppføring i databasen (gamle meldinger skal ikke vises)
     * og har derfor tilpasset koden til dette. Se kommentarer i metode
     */
    public  void sendDagens() {
         try {
                String dagens = jTextAreaDagens.getText();
        
                String SQLsjekk = ("SELECT * FROM dagens");
                Connection con = DriverManager.getConnection(Constants.db_url, Constants.db_user, Constants.db_pass);
                Statement sjekk = con.createStatement();
                ResultSet rs = sjekk.executeQuery(SQLsjekk);
                // lager en boolean
                boolean melding = true;
                // lager en string
                String dagensMelding = "";
                while (rs.next()) {
                    // setter string til dagensBeskjed fra database
                    dagensMelding = rs.getString("dagensBeskjed");
                    if (dagensMelding == null) {
                        // Om string er null, true
                        melding = true;
                    }
                    else {
                        // om string har innhold, false
                        melding = false;
                    }
                }
                // om det ikke eksisterer en melding i databasen / når melding = true
                if (melding) {
                String SQL = ("INSERT INTO dagens (dagensBeskjed, Bruker_brukerId) VALUES ('"+dagens+"', '"+Main.user.getId()+"')");      
                Statement setInfo = con.createStatement( );
                setInfo.executeUpdate(SQL);
                
                }
                // Om det eksisterer en melding kjør kun en update på dagensMelding og brukerId som sendte meldingen
                else {
                String SQL = ("UPDATE dagens SET dagensBeskjed='"+dagens+"', Bruker_brukerId = '"+Main.user.getId()+"'");
                Statement setInfo = con.createStatement( );
                setInfo.executeUpdate(SQL);
                }
        }
        catch (SQLException err) {
            System.out.println(err);
        }
        
                            
    }
    /**
     * Lik metoden i mainWindow for student. Kjøres når systemet starter 
     * for å hente data til Statistikk-tab
     */
    public void statistikkVisning() {
        try {

            String db_url = "jdbc:mysql://localhost:3306/slit";
            String db_user = "root";
            String db_pass = "root";
            
            System.out.println("The URL is: " + db_url);
            Connection con = DriverManager.getConnection(db_url, db_user, db_pass);
            
            Statement stmt = con.createStatement( );
            String SQL ="SELECT * FROM Statistikk";
            ResultSet result = stmt.executeQuery (SQL);
            
            int id_col = 0;
            String name = "";
            String surname ="";
            String dato = "";
            int antLeverte = 0;

            while (result.next() ) {
                id_col = result.getInt("Bruker_brukerId");
                name = result.getString("brukerFornavn");
                surname = result.getString("brukerEtternavn");
                dato = result.getString("modulfilDato");
                antLeverte = result.getInt("COUNT(sensurId)");
              //  System.out.println("ID: "+ " " + id_col +"     " +  "Fornavn: " + 
              //      "     " + name + "     " + "Etternavn: " +" "+ surname + "     " 
              //          + "Dato og klokkeslett:" + " " + dato + "     "
              //      + "Antall godkjente moduler:" + antLeverte);
                
                jTextAreaId.append(" " + "Bruker ID:"+ " " + id_col + newline);
                jTextAreaName.append(" " + "Fornavn:" + " " + name + newline);
                jTextAreaSurname.append(" " + "Etternavn:" + " " + surname + newline);
                jTextAreaDate.append(" " + "Aktivitet:" + " " + dato + newline);
                jTextAreaLeverte.append(" " + "Moduler med sensur:" + " " + antLeverte + newline);
                /**
                " +  "Fornavn: " + 
                    " " + name + "          " + "Etternavn: " +" "+ surname + "          " 
                        + "Dato og klokkeslett:" + " " + dato + "          "
                    + "Antall godkjente moduler:" + antLeverte + " "
                        + newline);
                        * /
                        
                // For å gjøre int om til string, om det trengs
                /**
                StringBuilder ID = new StringBuilder();
                    ID.append("");
                    ID.append(id_col);
                    String idString = ID.toString();
                
                StringBuilder leverte = new StringBuilder();
                    leverte.append("");
                    leverte.append(antLeverte);
                    String antLeverteString = leverte.toString();
               */     
            }
            
            
            
            
           
        }
          catch (SQLException err) {
            System.out.println( err.getMessage( ));
            
        } 
       
        
    }
    /**
     * For å vise profilen til innlogget bruker i høyremargen på systemet
     * @return 
     */
    public localUser profilVisning () {
        String user = Main.user.getUser();
        String rolle = Main.user.getRole();
        jLabelBruker.setText(user);
        jLabelRolle.setText(rolle);
        return Main.user;
    }
    /**
     * henter ut profilen til en bruker som er valgt i listen på Brukerliste-tab
     */
    public void hentProfil() {
        try {
                String profilNavn = jList1.getSelectedValue().toString();
                String SQL = ("SELECT * FROM Bruker where brukerEtternavn = '"+profilNavn+"'");
                
                Connection con = DriverManager.getConnection(Constants.db_url, Constants.db_user, Constants.db_pass);
             
                Statement stmt = con.createStatement( );
                ResultSet rs = stmt.executeQuery (SQL);
                
                int brukerId = 0;
                if (rs.next()) {
                    brukerId = rs.getInt("brukerId");
                    setBrukerNavn(rs.getString("brukerFornavn")); 
                    System.out.println("Vis profilen til" + " " + profilNavn);
                    StudentProfil profil = new StudentProfil();
                    profil.setVisible(true);
                }
                String SQL2 = ("SELECT * FROM Bruker WHERE brukerId = '"+brukerId+"'");
                
                
           
        }
        catch (SQLException err) {
            System.out.println(err);
        }
    }
    /**
     * Henter ut alle brukere med rollen Student i en liste på Brukerliste-tab
     */
    public void hentBrukere () {
         try {
            DefaultListModel DML = new DefaultListModel();
             Connection con = DriverManager.getConnection(Constants.db_url, Constants.db_user, Constants.db_pass);
       
               
                String SQL = ("SELECT * from Bruker WHERE brukerRolle = 'student'");      
                String brukerFornavn = "";
                String brukerEtternavn = "";
                Statement hentBrukere = con.createStatement( );
                ResultSet rs = hentBrukere.executeQuery (SQL);
                
                    while (rs.next()) {
                      brukerFornavn = rs.getString("brukerFornavn");
                      brukerEtternavn = rs.getString("brukerEtternavn");
                      DML.addElement (brukerEtternavn);
                    //  arrayList.add(brukerFornavn + brukerEtternavn);
                }
                jList1.setModel(DML);
        
        }
        catch (SQLException err) {
            System.out.println(err);
        }
    }
    /**
     * Henter ut eksisterende melding på hjem-tab.
     */
     public void hentDagens() {
        try {
            
            String SQL = ("SELECT dagensBeskjed FROM dagens");
            Connection con = DriverManager.getConnection(Constants.db_url,Constants.db_user, Constants.db_pass);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(SQL);
            String dagensMelding = "";
            while (rs.next()) {
            dagensMelding = rs.getString("dagensBeskjed");
            jTextAreaDagens.append(dagensMelding);
            }
        }
        catch (SQLException err) {
            System.out.println(err);
        }
            
    }
     /**
      * Henter lagrede møtetider på Møte-tab
      */
    public void hentMøte () {
         try {
            DefaultListModel DML = new DefaultListModel();
             Connection con = DriverManager.getConnection(Constants.db_url, Constants.db_user, Constants.db_pass);
       
               
                String SQL = ("SELECT  * from møte");      
                int møteId = 0;
                String møteTidspunkt = "";
                String møteSted = "";
                Statement hentmøte = con.createStatement( );
                ResultSet rs = hentmøte.executeQuery (SQL);
                
                    while (rs.next()) {
                      møteId = rs.getInt("møteId");
                      møteTidspunkt = rs.getString("møteTidspunkt");
                      møteSted = rs.getString("møteSted");
                      DML.addElement ("Møte ID:"+ " " +møteId + "   " + "Tidspunkt:" + " " + møteTidspunkt+ "   " + "Sted:" + " "+ møteSted);
                    //  arrayList.add(brukerFornavn + brukerEtternavn);
                }
                jListMøte.setModel(DML);
        
        }
        catch (SQLException err) {
            System.out.println(err);
        }
    }
    private void jTabbedPaneBrukerlisteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneBrukerlisteMouseClicked
        // TODO add your handling code here:
        db.hentGammelBeskjed();
        jTextAreaInfo.setText(getGenerellModul());
    }//GEN-LAST:event_jTabbedPaneBrukerlisteMouseClicked

    private void jButtonLagreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLagreActionPerformed
        // Setter møtetider
        // Setter variablene til queries
        tidspunkt = jTextFieldTidspunkt.getText();
        
        // Resten av verdiene er tekst også i databasen
        møtested = jTextFieldSted.getText();
        // kaller sendMøteInformasjon, metode som sender møtetid til databasen
        sendMøteInformasjon();

        jTextFieldSted.setText("");
        jTextFieldTidspunkt.setText("");
       

        JOptionPane.showMessageDialog(null, "<Møtet er blitt lagret>", "Alert", JOptionPane.INFORMATION_MESSAGE);
        // Kaller også hentMøte for å oppdatere møtelisten med en gang man lagrer et nytt møte
        hentMøte();

        }
    /**
     * Metoden kaller metode fra db.java, der logikken ligger
     */
        private void sendMøteInformasjon() {
            if (Main.user != null)
            db.sendMøteInfo(tidspunkt, møtested);

    }//GEN-LAST:event_jButtonLagreActionPerformed

    private void jTextFieldStedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStedActionPerformed

    private void jButtonLagreInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLagreInfoActionPerformed
        // TODO add your handling code here:
        setGenerellModul(jTextAreaInfo.getText());
        System.out.println(getGenerellModul());
        slit.db.generellInfo();
        slit.db.hentGammelBeskjed();
    }//GEN-LAST:event_jButtonLagreInfoActionPerformed

    private void jButtonModul14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul14ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 14");
        moduleInformationWindowForeleser modul14 = new moduleInformationWindowForeleser();
        modul14.hentPublisert();
        modul14.setVisible(true);
    }//GEN-LAST:event_jButtonModul14ActionPerformed

    private void jButtonModul13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul13ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 13");
        moduleInformationWindowForeleser modul13 = new moduleInformationWindowForeleser();
        modul13.hentPublisert();
        modul13.setVisible(true);
    }//GEN-LAST:event_jButtonModul13ActionPerformed

    private void jButtonModul12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul12ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 12");
        moduleInformationWindowForeleser modul12 = new moduleInformationWindowForeleser();
        modul12.hentPublisert();
        modul12.setVisible(true);
    }//GEN-LAST:event_jButtonModul12ActionPerformed

    private void jButtonModul11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul11ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 11");
        moduleInformationWindowForeleser modul11 = new moduleInformationWindowForeleser();
        modul11.hentPublisert();
        modul11.setVisible(true);

    }//GEN-LAST:event_jButtonModul11ActionPerformed

    private void jButtonModul10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul10ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 10");
        moduleInformationWindowForeleser modul10 = new moduleInformationWindowForeleser();
        modul10.hentPublisert();
        modul10.setVisible(true);
    }//GEN-LAST:event_jButtonModul10ActionPerformed

    private void jButtonModul9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul9ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 9");
        moduleInformationWindowForeleser modul9 = new moduleInformationWindowForeleser();
        modul9.hentPublisert();
        modul9.setVisible(true);
    }//GEN-LAST:event_jButtonModul9ActionPerformed

    private void jButtonModul8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul8ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 8");
        moduleInformationWindowForeleser modul8 = new moduleInformationWindowForeleser();
        modul8.hentPublisert();
        modul8.setVisible(true);
    }//GEN-LAST:event_jButtonModul8ActionPerformed

    private void jButtonModul7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul7ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 7");
        moduleInformationWindowForeleser modul7 = new moduleInformationWindowForeleser();
        modul7.hentPublisert();
        modul7.setVisible(true);
    }//GEN-LAST:event_jButtonModul7ActionPerformed

    private void jButtonModul6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul6ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 6");
        moduleInformationWindowForeleser modul6 = new moduleInformationWindowForeleser();
        modul6.hentPublisert();
        modul6.setVisible(true);
    }//GEN-LAST:event_jButtonModul6ActionPerformed

    private void jButtonModul5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul5ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 5");
        moduleInformationWindowForeleser modul5 = new moduleInformationWindowForeleser();
        modul5.hentPublisert();
        modul5.setVisible(true);
    }//GEN-LAST:event_jButtonModul5ActionPerformed

    private void jButtonModul4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul4ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 4");
        moduleInformationWindowForeleser modul4 = new moduleInformationWindowForeleser();
        modul4.hentPublisert();
        modul4.setVisible(true);
    }//GEN-LAST:event_jButtonModul4ActionPerformed

    private void jButtonModul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul3ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 3");
        moduleInformationWindowForeleser modul3 = new moduleInformationWindowForeleser();
        modul3.hentPublisert();
        modul3.setVisible(true);
    }//GEN-LAST:event_jButtonModul3ActionPerformed

    private void jButtonModul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul2ActionPerformed
        // TODO add your handling code here:
        setModulTrykket("modul 2");
        moduleInformationWindowForeleser modul2 = new moduleInformationWindowForeleser();
        modul2.hentPublisert();
        modul2.setVisible(true);
    }//GEN-LAST:event_jButtonModul2ActionPerformed

    private void jButtonModul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModul1ActionPerformed

        // TODO add your handling code here:
        setModulTrykket("modul 1");
        moduleInformationWindowForeleser modul1 = new moduleInformationWindowForeleser();
        modul1.hentPublisert();
        modul1.setVisible(true);
    }//GEN-LAST:event_jButtonModul1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setValgtBruker(jList1.getSelectedValue().toString());
        hentProfil();
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new lastNed().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Sensur().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sendDagens();
        JOptionPane.showMessageDialog(null, "Dagens melding er nå lagt ut");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindowForeleser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindowForeleser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindowForeleser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindowForeleser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindowForeleser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonLagre;
    private javax.swing.JButton jButtonLagreInfo;
    private javax.swing.JButton jButtonModul1;
    private javax.swing.JButton jButtonModul10;
    private javax.swing.JButton jButtonModul11;
    private javax.swing.JButton jButtonModul12;
    private javax.swing.JButton jButtonModul13;
    private javax.swing.JButton jButtonModul14;
    private javax.swing.JButton jButtonModul2;
    private javax.swing.JButton jButtonModul3;
    private javax.swing.JButton jButtonModul4;
    private javax.swing.JButton jButtonModul5;
    private javax.swing.JButton jButtonModul6;
    private javax.swing.JButton jButtonModul7;
    private javax.swing.JButton jButtonModul8;
    private javax.swing.JButton jButtonModul9;
    private javax.swing.JButton jButtonSlett;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBruker;
    private javax.swing.JLabel jLabelModuler109;
    private javax.swing.JLabel jLabelModuler110;
    private javax.swing.JLabel jLabelRolle;
    private javax.swing.JLabel jLabelSted;
    private javax.swing.JLabel jLabelTidspunkt;
    private javax.swing.JLabel jLabelTittel;
    private javax.swing.JList jList1;
    private javax.swing.JList jListMøte;
    private javax.swing.JPanel jPanelBotMain;
    private javax.swing.JPanel jPanelHjem;
    private javax.swing.JPanel jPanelInnlevering;
    private javax.swing.JPanel jPanelLeftCentre;
    private javax.swing.JPanel jPanelLeftLeft;
    private javax.swing.JPanel jPanelLeftMain;
    private javax.swing.JPanel jPanelLeftRight;
    private javax.swing.JPanel jPanelLeftRightRight;
    private javax.swing.JPanel jPanelModuler;
    private javax.swing.JPanel jPanelMøte;
    private javax.swing.JPanel jPanelMøteCentre;
    private javax.swing.JPanel jPanelMøteLeft;
    private javax.swing.JPanel jPanelMøteRight;
    private javax.swing.JPanel jPanelMøteTop;
    private javax.swing.JPanel jPanelMøtebot;
    private javax.swing.JPanel jPanelRightMain;
    private javax.swing.JPanel jPanelStatistikk;
    private javax.swing.JPanel jPanelStatistikkMain;
    private javax.swing.JPanel jPanelTopBot;
    private javax.swing.JPanel jPanelTopCentre;
    private javax.swing.JPanel jPanelTopMain;
    private javax.swing.JPanel jPanelTopTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPaneMeny;
    private javax.swing.JScrollPane jScrollPaneModuloversikt;
    private javax.swing.JSeparator jSeperatorLeftLeft;
    private javax.swing.JSeparator jSeperatorLeftRight;
    private javax.swing.JSeparator jSeperatorTopBot;
    private javax.swing.JTabbedPane jTabbedPaneBrukerliste;
    private javax.swing.JTextArea jTextAreaDagens;
    private javax.swing.JTextArea jTextAreaDate;
    private javax.swing.JTextArea jTextAreaId;
    private javax.swing.JTextArea jTextAreaInfo;
    private javax.swing.JTextArea jTextAreaLeverte;
    private javax.swing.JTextArea jTextAreaName;
    private javax.swing.JTextArea jTextAreaSurname;
    private javax.swing.JTextField jTextFieldSted;
    private javax.swing.JTextField jTextFieldTidspunkt;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTree jTreeMeny;
    private javax.swing.JLabel profilTitle;
    // End of variables declaration//GEN-END:variables
}
